### ISSUE TITLE
这代码能在gae上运行吗？

### ISSUE THREAD

**Issue by sjmr** [pandolia/qqbot#10]
RT，感谢作者开源

**Comment by pandolia** [comment]
gae 是什么？理论上可以运行 python 的系统应该都可以用。

**Comment by sjmr** [comment]
google 的云平台，感觉好像不行，google 做了一些限制，有一些不同

**Comment by pandolia** [comment]
哦。那你能在gae云平台上使用 requests 库吗？如果可以用 requests 库，那应该可以运行 qqbot 了。
