### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by shangguan1997** [pandolia/qqbot#102]
因为导入的定时模块的问题导致打包失败。

**Comment by pandolia** [comment]
定时模块 apscheduler 导致的打包问题，你看下这篇文章能不能解决 http://www.bbsmax.com/A/qVdepor5Pg

**Comment by pandolia** [comment]
Windows 下， 建议使用 virtualenv 将 qqbot 以及 pyinstaller 安装至独立的运行环境中，然后利用此环境中的 pyinstaller 进行打包。

用以下脚本创建 qqbot 的虚拟环境，将 qqbot 及其依赖的库安装至 %UserProfile%/PyVenv/qqbot-env/lib/site-packages 目录下：

    pip install virtualenv
    
    c:
    mkdir %UserProfile%\PyVenv
    cd %UserProfile%\PyVenv
    virtualenv --no-site-packages qqbot-env

    %UserProfile%\PyVenv\qqbot-env\Scripts\activate

    pip install requests==2.7.0
    pip install certifi==2015.4.28
    pip install flask==0.12
    pip install apscheduler==3.3.1
    pip install qqbot

其中 %UserProfile% 是用户主目录，Win7中为 C:\Users\xxx 目录。

如果需要使用 pyinstaller 打包，还需要安装 pyinstaller 和 pypiwin32 ：

    pip install pyinstaller==3.2.1
    pip install pypiwin32==219

然后在 %UserProfile%\PyVenv\qqbot-env 下新建一个目录 myapp ：
    
    cd %UserProfile%\PyVenv\qqbot-env
    mkdir myapp
    cd myapp

在该目录下新建一个 main.py ，内容为：

    from qqbot import Main; Main()

再新建一个 hook-ctypes.macholib.py ，内容为：

    from PyInstaller.utils.hooks import copy_metadata
    datas = copy_metadata('apscheduler')

最后，输入以下命令将 main.py 打包为 dist\main.exe

    ..\Scripts\pyinstaller -F main.py --additional-hooks-dir=.

我在 Python2.7.10, pip7.0.3 中已经测试过了，打包和运行都没有问题。

**Comment by pandolia** [comment]
另外，请单独测试一下 main.py 文件能不能打包，内容只有 ：

    from qqbot import Main; Main()

如果此文件可以打包并正常运行，那也可能是你的程序中引入了其他模块而导致的问题。

**Comment by pandolia** [comment]
@shangguan1997 安装 pyintaller 的开发版应该是可以解决打包问题： pip install git+https://github.com/pyinstaller/pyinstaller.git

**Comment by shangguan1997** [comment]
OK 我试试

**Comment by shangguan1997** [comment]
还是找不到APSchedure

**Comment by pandolia** [comment]
可能需要python2.7.10及以上的版本。
