### ISSUE TITLE
在参数文件中配置了"monitorTables" : ['buddy']后导致内存占用不断增大

### ISSUE THREAD

**Issue by lixindreamer** [pandolia/qqbot#107]

**Comment by pandolia** [comment]
有可能是后台获取并更新完联系人列表之后，老的列表没有及时销毁。我再审查一下代码。你先关闭此功能吧。

**Comment by pandolia** [comment]
鉴于联系人获取接口实在太不稳定了，因此从 v2.2.1 版开始去掉 monitorTables 的功能。
v2.2.1版采用 sqlite3 数据库保存联系人，现在应该是没有内存问题了。
