### ISSUE TITLE
v2.1.15 版发布，修正群成员无法获取的问题，感谢 @waylonwang

### ISSUE THREAD

**Issue by pandolia** [pandolia/qqbot#110]
昨天开始，由于 qun.qq.com 的 search_group_members 接口无法使用 w.qq.com 的 cookie，因此无法获取群成员列表，由此导致了所有和群成员相关的功能都无法使用了（包括 list group-member, group-manage, @me 等）。非常感谢 @waylonwang 迅速的提供了用 qinfo.clt.qq.com 的接口获取群成员信息的代码，完美的修复了此问题，目前所有相关功能都已恢复正常使用，另外还带了一个好处就是现在可以获取到完整的群名片（以往群名片如果太长会被截断）。

其他修改：

1） 增加了后台获取联系人的间歇时间，每个列表获取完后 sleep 15 秒，所有列表获取完后 sleep 至少 10 分钟。另外，建议暂不要使用 特别监视列表 的功能，避免过于频繁的在后台获取联系人， @lixindreamer 反映开启此功能后 python 的内存占用不断增大，尚不清楚是否确实是程序引起的问题。

2） 测试发现 qun.qq.com 中的 群管理接口中除了 禁言 功能外，其他功能也无法使用了。因此在文档中注明了这些功能暂无法使用。相关的代码暂未删除。

3） 修复了 python3.4 下无法使用 b'%s' % 'xxx' 的 bug

**Comment by jim4node** [comment]
太及时了, 谢谢@waylongwang
