### ISSUE TITLE
v2.1.16已发布，恢复群管理功能，再次感谢 @waylonwang

### ISSUE THREAD

**Issue by pandolia** [pandolia/qqbot#113]
1） 恢复群管理功能（踢人、设置群名片、设置|取消管理员），再次感谢 @waylonwang ，他提供了用 qinfo.clt.qq.com 的接口实现上述功能的代码。

2） 修正踢人和设置群名片成功后更新缓存的过程中的 bug 。

**Comment by sjdy521** [comment]
虽然有 qinfo.clt.qq.com 的接口可以根据指定的群号和qq号踢人，但是没办法批量获取全部的群号和每个群成员的qq号了，我这样理解对吧？

**Comment by pandolia** [comment]
@sjdy521 批量获取全部群号和没个群成员的qq号都没问题，现在的问题是QQ关闭了一个很重要的接口 get_friend_uin2，所以没有办法将qq号和uin绑定起来，收到消息时也无法知道到底是哪个qq号发过来的消息。
当然，可以按您之前建议的，可以对比w.qq.com返回的name--uin 和 qinfo.clt.qq.com返回的name--qq，根据两个接口中的name来绑定大部分成员的qq--uin，但是，当成员存在同名的情况时，这种对比方法就会失效。
我目前正在按以上思路修改程序，可以解决大部分成员的qq-uin绑定的问题，但对于同名现象就无能为力了。

**Comment by sjdy521** [comment]
可我现在发现的问题就是没办法通过 `http://qun.qq.com/cgi-bin/qun_mgr/search_group_members` 批量获取到真实的群成员qq号码了

**Comment by pandolia** [comment]
是的，这个接口也失效了，@waylonwang 提供了使用 qinfo.clt.qq.com 接口获取群成员qq的代码，详见 qsession.py的fetchGrouoMember方法。
这个接口其实更好，返回的群名片是完整的。

**Comment by pandolia** [comment]
@sjdy521 http://qinfo.clt.qq.com/cgi-bin/qun_info/get_group_members_new 可以获取到完整的群成员qq以及名片等。

**Comment by pandolia** [comment]
你说的这两个接口都没用了
http://qun.qq.com/cgi-bin/qun_mgr/delete_group_member
http://qun.qq.com/cgi-bin/qun_mgr/set_group_card

我现在用的是
http://qinfo.clt.qq.com/cgi-bin/qun_info/delete_group_member
http://qinfo.clt.qq.com/cgi-bin/qun_info/set_group_admin
http://qinfo.clt.qq.com/cgi-bin/qun_info/set_group_shutup
http://qinfo.clt.qq.com/cgi-bin/qun_info/set_group_card

详见 https://github.com/pandolia/qqbot/blob/master/qqbot/groupmanager.py

以上接口及相关代码都是 @waylonwang 提供的，再次向他表示感谢。

**Comment by sjdy521** [comment]
好的 感谢分享
