### ISSUE TITLE
卡死及发送消息问题

### ISSUE THREAD

**Issue by Pipapa** [pandolia/qqbot#116]
频繁出现多次发送相同消息。还有发送的消息有时候顺序不对。是否可以通过延时发送解决？？出现过一次卡死内存占用过大问题。

**Comment by pandolia** [comment]
重复发消息主要是因为 QQ 服务器返回 1202 代码的原因。v2.1.17版已针对此问题在 bot.SendTo 接口中增加了一个参数： reSendOn1202 ，若此参数为 True （默认值），则发消息时如果 QQ 服务器返回 1202 代码（表明发消息可能失败），还会继续发送 3 次，直至返回 0 代码， 若此参数为 False ，则不会尝试重发。
设为 True 在绝大部分情况下能保证消息一定能发出去，但缺点是有时一条消息会重复发送。设为 False 则相反，消息不会重复发送，但有时消息发送不出去。
总之因为这个 1202 代码的不确定性，没有完美的解决办法。

**Comment by pandolia** [comment]
顺序不对通过延时应该是可以解决的。内存问题，可能是后台获取联系人并更新的问题，这一部分的代码我还需要审查一下，不清楚是否是联系人列表没有及时销毁或者压根就没销毁的原因。你可以在启动时用 qqbot -fi -1 来关闭后台更新。

**Comment by Pipapa** [comment]
经常频繁掉线,请问有监控是否掉线函数,自定义掉线操作?

**Comment by pandolia** [comment]
可以设置为掉线时重新启动。

**Comment by pandolia** [comment]
暂时没有自定义掉线操作的入口。确实需要的话，你可以在 qqbotcls.py 的第 153 行之前添加你的自定义掉线操作。

**Comment by pandolia** [comment]
新的 v2.2.1 版已基本修复群成员资料的获取问题以及其他相关问题。卡死问题应该不存在了，仅在最开始时需要获取联系人列表会卡顿几秒。
内存问题现在应该是不存在了，现在采用 sql3lite 数据库保存联系人资料，全部保存在硬盘上。
