### ISSUE TITLE
加入新群后，传给onQQMessage的contact对象各属性为空

### ISSUE THREAD

**Issue by cutepig49** [pandolia/qqbot#118]
比如nick和qq属性

**Comment by pandolia** [comment]
是的，这个时候可以手工 update 一下，执行一下 bot.Update('group') 刷新一下群列表。程序对这种情况没有自动去调用 Update 的原因还是基于效率的考虑，有时后 bot.Update 要卡几秒钟，为了这种比较少见的情况似乎不值得。所以还是用户由自己主动调用。

**Comment by cutepig49** [comment]
谢谢回复
另外，bot.Update的调用之后，当前的contact会随之更新吗？
比如:
```python
@QQBotSlot
def onQQMessage(bot, contact, member, content):
    if contact.qq == "":
        bot.Update('group')
    print(contact.qq)   #这里是否已经获得QQ号了？

**Comment by pandolia** [comment]
不会

**Comment by pandolia** [comment]
update后return就可以了。过一两条消息后就有了

**Comment by pandolia** [comment]
v2.2.1版已针对此问题增加了 “当收到新加的联系人的消息时、自动Update“ 的代码 。
