### ISSUE TITLE
是smart qq协议变更了么？

### ISSUE THREAD

**Issue by chenhouwu** [pandolia/qqbot#121]
一直出现

```
请求“http://s.web2.qq.com/api/get_friend_uin2”时出现 超时，html='<html><head><title>A...0</h3></body></html>'
```

此时，登陆，接收、发送消息都正常

**Comment by palmchou** [comment]
在收到 群消息后 出现

    [2017-04-17 11:48:25] [DEBUG] 第19次请求“http://s.web2.qq.com/api/get_friend_uin2”时出现 超时，html='<html><head><title>A...0</h3></body></html>'

之后获取 member.qq 会失败。

刚要 file issue 呢

**Comment by pandolia** [comment]
get_friend_uin2的接口已经无法使用了，暂时没有办法获取到成员的实际QQ以及其他资料。我已经push了一个临时版本上去了。收发消息都ok，但是所有成员资料都获取不到，收到群消息的时候，也只能显示群的资料，显示不出成员的资料。

**Comment by chenhouwu** [comment]
@pandolia 
`http://s.web2.qq.com/api/get_group_info_ext2` 这个接口可以的，result['cards'][i]为一个objec，里面有两个属性：'muin'和'card', 其中 'muin'即为member的qq好，card为该member在群里的名字

**Comment by pandolia** [comment]
我最开始就是用的 get_group_info_ext2 ，这个接口的问题是有时候只能返回 uin ，其他资料（包括名称）都返回不了。你登录后几个小时后再请求看看它的返回结果。
另外，uin 不是成员的 QQ 号，是每次登录分配的一个 临时ID。

**Comment by pandolia** [comment]
等晚一点我再改回用 get_group_info_ext2 的接口吧。

**Comment by pandolia** [comment]
新的 v2.2.1 版已基本修复群成员资料的获取问题以及其他相关问题。
