### ISSUE TITLE
获取群消息问题

### ISSUE THREAD

**Issue by cloudisme** [pandolia/qqbot#122]
刚接触， 只用了小部分功能，目前发现有3个问题，请教下：
1、onQQMessage监听群消息时，有几秒的延迟，而buddy消息则不会；
2、监听群消息时，经常有漏掉的情况；
3、监听群消息时，获取不到发消息人的qq及昵称等信息，只有uin；

想问下上面的情况，是本来就有的现象，还是可能我这边的环境问题？

PS：qqbot很赞很赞，感谢你贡献了这么一个有趣的东西

**Comment by pandolia** [comment]
感谢！这些现象是本来就有的，最近腾讯关闭了几个重要的接口，这个项目都有点残了，涉及到群成员资料相关的功能几乎都无法使用了。等我尽快修复一下吧。

**Comment by cloudisme** [comment]
支持支持！
我这边也研究下Smart QQ的协议

**Comment by pandolia** [comment]
新的 v2.2.1 版已基本修复群成员资料的获取问题以及其他相关问题。

**Comment by cloudisme** [comment]
嗯看到了，现在群消息速度很快，感谢，给力给力！
我这边测试，目前是可以拿到群成员昵称了，qq号就一直是NULL

**Comment by cloudisme** [comment]
最新测试，qq号可以获取了，NULL是少数情况，手动点赞
