### ISSUE TITLE
v2.2.1发布， 基本上修复了因 get_friend_uin2 接口被关闭而引起的一系列问题

### ISSUE THREAD

**Issue by pandolia** [pandolia/qqbot#124]
1） 基本上修复了因 get_friend_uin2 接口被关闭而引起的一系列问题。但当 好友/群/群成员 存在同名现象或名称中含特殊字符时，还是存在无法绑定其实际 QQ 的问题。

2） 由于 smartqq 中获取联系人列表的接口实在太不稳定了，因此关闭后台联系人获取，联系人列表只有在第一次需要用到的时候才会去请求相应的接口获取列表并更新至联系人数据库内（第二次用时可以直接读数据库）。由此去掉了 onNewContact 、 onLostContact 和 onFetchComplete 三个回调函数，并去掉了 fetchInterval 和 monitorTables 两个配置选项。

3） 整理、优化联系人列表和资料的数据结构，并采用 sqlite3 数据库保存联系人列表和资料。增加联系人的各属性的详细解释，同时，各属性不再不加区分的保存为 str 对象，而是根据需要保存为 str 对象或 int 对象。联系人属性详见 [qcontact-attr](https://github.com/pandolia/qqbot/blob/master/qcontact-attr.md)

4） 利用原 2.1 版开发的机器人程序需要进行以下改动：

1. ~/.qqbot-tmp/ 目录下的配置文件名应改为 v2.2.conf ，并删除其中的 fetchInterval 和 monitorTables 选项

2. 删除机器人程序中的 onNewContact 、 onLostContact 和 onFetchComplete 三个回调函数。如果确实需要 onFetchComplete ，可将其中的代码放到 onStartupComplete 中，并将启动方式设置为 “联系人列表获取完成后再启动” （将 startAfterFetch 选项设置为True）。

3. 根据联系人对象（ QContact 对象）的各属性的类型和含义的变化对原有的代码进行调整。

**Comment by chenhouwu** [comment]
腾讯api访问极度不稳定，
干净（清除pickle文件）开机不久就会出现下面的消息
```
[2017-04-22 00:42:49] [DEBUG] 第1次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求 被拒绝错误，html='{"errmsg":"error","retcode":1202}'
[2017-04-22 00:43:50] [DEBUG] 第2次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求 被拒绝错误，html='{"errmsg":"error","retcode":1202}'
[2017-04-22 00:44:51] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求 被拒绝错误
[2017-04-22 00:44:51] [DEBUG] html='{"errmsg":"error","retcode":1202}'
[2017-04-22 00:44:51] [CRITICAL] QQBOT 异常停止（code=203）
```

**Comment by pandolia** [comment]
我这边倒是没这个问题，可以正常挂1~2天。

**Comment by chenhouwu** [comment]
升级前的2.1.x版正常，
升级成2.2.x就这样了。。。

**Comment by pandolia** [comment]
v2.2.2已发布。 list  等命令/接口的参数增加 :like: 字段，提供强大的联系人搜索功能。示例：

    # 列出名称中含有 “李” 的好友
    qq list buddy :like:李

    # 列出 QQ 中含有 “234” 的群
    qq list group :like:234

    # 列出备注名中含有 jack 的好友
    qq list buddy mark:like:jack

    # 列出 群“456班” 的中名称中含有 “李” 的成员
    qq list group-member 456班 :like:李

    # 列出 群“456班” 中名片中含有 “mike” 的成员
    qq list group-member 456班 card:like:mike

    # 列出的 讨论组“xx小组” 中名为 jack 的好友
    qq list discuss-member :like:小组 jack

**Comment by chenhouwu** [comment]
我试试v2.2.2吧。
v2.2.1还是不行，迅速地失效。

**Comment by pandolia** [comment]
v2.2.2就增加了一个 like 而已。

**Comment by pandolia** [comment]
不知道为什么会失效。v2.1.x 和 v2.2.1 收消息的部分是没有改过的。

**Comment by chenhouwu** [comment]
换了个qq号，好了

**Comment by chenhouwu** [comment]
换的qq号很快又不行了。。。

**Comment by pandolia** [comment]
2.2的获取联系人列表的频率比2.1的低多了，获取频率接近于0了，只有在需要用到的时候才会去获取。不像2.1那样不停的在后台获取。
你试试用 qqbot -saf 的方式启动看看，启动之前全部获取好，后面几乎不再获取了。

**Comment by chenhouwu** [comment]
不行。。。难道是我的ip地址上黑名单了？
腾讯真是的。。。
别家都专门提供api，他家这样搞

**Comment by pandolia** [comment]
要不改一下basicqsession.py里面的smartrequest方法，直接忽略这个错误。

**Comment by palmchou** [comment]
我这里也会出现类似的错误。很奇怪
    [2017-04-23 13:55:34] [DEBUG] 第1次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误，html='{"errmsg":"error","retcode":1202}'
    [2017-04-23 13:56:35] [DEBUG] 第2次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误，html='{"errmsg":"error","retcode":1202}'

**Comment by chenhouwu** [comment]
我将`smartRequest`函数默认参数改成`repeatOnDeny=20`，还好。
虽然仍然经常出现这个错误，但是一般两三次就好了，不会退出，
之后仍然可以正常接收和回复消息。

**Comment by pandolia** [comment]
@chenhouwu 这么说的话，直接忽略这个错误也是可以的，那可以改一下 basicqsession.py 中 Poll 方法的第一句，传递参数的时候，加一个 expectedCodes = (0, 100003, 100100, 1202) ，就可以了。

        result = self.smartRequest(
            url = 'https://d1.web2.qq.com/channel/poll2',
            data = {
                'r': JsonDumps({
                    'ptwebqq':self.ptwebqq, 'clientid':self.clientid,
                    'psessionid':self.psessionid, 'key':''
                })
            },
            Referer = ('http://d1.web2.qq.com/proxy.html?v=20151105001&'
                       'callback=1&id=2'),
            expectedCodes = (0, 100003, 100100, 1202)
        )

**Comment by pandolia** [comment]
改 smartRequest 函数默认参数不太合适，会影响其他接口的请求。

**Comment by cloudisme** [comment]
辛苦辛苦，之前我发现的一些问题都基本解决了，感谢

**Comment by pandolia** [comment]
@chenhouwu v2.2.4 已经加入了忽略 poll 返回 1202 的代码。

**Comment by chenhouwu** [comment]
👌
