### ISSUE TITLE
如何主动控制机器人发送消息

### ISSUE THREAD

**Issue by palmchou** [pandolia/qqbot#125]
作者你好，感谢开发了 qqbot 项目，使用了一段时间，非常方便我们当前的项目。现有一个关于 主动控制 bot 发送消息给指定成员的问题。

2.0 时，可以拿到 bot 实例。直接调用 sentTo()

2.1 时我 subclass 了 QQBot 类，override onQQMessage 等方法。在主进程中 instantiate 它之后，再创建子线程 RunBot。这样变相拿到了 bot 实例。也可以 程序化的 控制机器人主动发送消息。

更新了 2.2 之后，尝试像 2.1 一样主线程实例化 QQBot 类，子线程再 RunBot。现在会遇到 sqlite 不能在 不同线程使用的 exception.

不知道对这个问题有什么见解和建议，谢谢！。

**Comment by pandolia** [comment]
注册回调函数（比如 onInterval 或 qqbotsched），然后在回调函数里面发消息能否达到你们的目的？

不管哪个版本，bot 实例的所有接口（ SendTo/List/GroupXXX 等）都不是线程安全的，不建议在子线程里面去调用这些接口。

或者你可以试试，将 qqbot 作为独立的进程，在你们自己的程序里面调用 qq 命令行工具或者 http-api 接口。

另外，你还可以试下写一个插件文件，比如下面这样：

    from qqbot import QQBot; bot = QQBot._bot

    cl = bot.List('buddy', 'jack')
    if cl:
        b = cl[0]
        bot.SendTo(b, 'hello')

将以上文件另存为 myplugin.py ，这样，每次你在 qqbot 进程的外部运行 “qq plug myplugin” 的时候，这个文件里面的所有代码都会被插入到 qqbot 进程中的主线程里面运行一次。

**Comment by pandolia** [comment]
可能将 qcontactdb/contactdb.py 文件第 101 行的 **class ContactDB(object)** 改为： **class ContactDB(threading.local)** 可以解决你的问题。

**Comment by palmchou** [comment]
@pandolia ，感谢！修改了 ContactDB(threading.local) 可以继续使用 v2.2 了。
