### ISSUE TITLE
插件名叫qqbot-script时会导致加载时找不到回调函数或定时任务

### ISSUE THREAD

**Issue by KurumiSerori** [pandolia/qqbot#126]
尝试用示例中的定时任务也不行，一定要改成其他名字才可以

**Comment by pandolia** [comment]
插件本质是一个python模块，要按模块的命名规则来。

**Comment by pandolia** [comment]
跟变量的命名规则一样

**Comment by KurumiSerori** [comment]
请问能明确说一下命名为qqbot-script的问题在哪吗？我是一名python初学者，因此不太能理解哪里会与模块的命名规则产生冲突？我个人测试叫qqbot-test之类的不会产生问题，只是最开始就起了qqbot-script这个名字才发现的。

**Comment by pandolia** [comment]
我测试了一下，qqbot-script.py 这个名字没问题。可能你还有另外一个 qqbot-script.py 文件，实际上加载的是那个文件。
![qq 20170425092744](https://cloud.githubusercontent.com/assets/13767061/25365233/f6e6937e-2999-11e7-99dc-131842ad529f.png)

**Comment by KurumiSerori** [comment]
发现python安装目录下有个Scripts文件夹下有同名文件...这个是qqbot安装时自动释放进的文件么？
感觉可以加个加载插件的时候显示插件路径的功能/选项 XD
