### ISSUE TITLE
协议好像又有问题了？

### ISSUE THREAD

**Issue by suxiaojack** [pandolia/qqbot#127]
就是最简单的sample.py代码python 2.7下运行，能登录。无法接收消息。给qq发送信息-hello之类无反应。
用qq命令可以发送消息。就是无法更新接收消息。

**Comment by huangenyan** [comment]
好像 https://d1.web2.qq.com/channel/poll2 已经彻底用不了了……

**Comment by GeiliCode** [comment]
我也是无法收到新消息...

**Comment by pandolia** [comment]
是的。。。很杯具。。。

**Comment by huangenyan** [comment]
尝试抓包拿不到收消息的数据，现在web QQ应该走的不是HTTP或者HTTPS了，就很麻烦……

**Comment by pandolia** [comment]
现在好像又好了。

**Comment by GeiliCode** [comment]
我的也好了...

**Comment by StayFeelFoolish** [comment]
又壞了嗎？
