### ISSUE TITLE
第6次请求“http://s.web2.qq.com/api/get_group_info_ext2”时出现 请求被拒绝错误

### ISSUE THREAD

**Issue by univert** [pandolia/qqbot#128]
这个链接请求被拒绝，但是qqbot还是能收到消息

**Comment by pandolia** [comment]
登录时间过长之后，请求此接口尝试更新群成员列表时确实会出现这个错误。
当群内有了新成员的时候，该成员发言的时候 qqbot 发现本地数据库找不到这个成员，这时会尝试去更新群成员列表。如果该成员不发言就不影响其他功能。
