### ISSUE TITLE
二维码 http 服务器 ip

### ISSUE THREAD

**Issue by huangzk** [pandolia/qqbot#132]
qqbot启动后通过生成的http://10.8.74.45:8189/qqbot/qrcode 去扫描二维码第一次都显示过期，需要刷新一下网页二维码才是最新的

**Comment by pandolia** [comment]
感谢反馈。刚才测试了一下，当 ~/.qqbot-tmp 路径下存在未删除的 png 文件是确实会有这个问题。已经 push 了一个 commit 修正了此 bug 。并将二维码的 url 地址改为： http://{httpServerIP}:{httpServerPort}/{pngid}

**Comment by huangzk** [comment]
hello,是这样的，如果把二维码url的地址改掉的话，我静态页面怎么去获取对应的pngID。。。我需要在页面展示二维码，有接口可以获取到二维码url地址吗。

**Comment by pandolia** [comment]
我刚才又测试了一下。原来的 http://10.8.74.45:8189/qqbot/qrcode 扫描二维码第一次过期，其实并不是代码的问题。而是因为第一次显示的浏览器上次的缓存，实际上根本就没去请求那个 url 。只要是 url 是固定的，就存在这个问题。后面改成 http://{httpServerIP}:{httpServerPort}/{pngid} 因为每次 url 都是变的，所以不需要刷新。

**Comment by pandolia** [comment]
我已经修改了代码，url 还是  http://{httpServerIP}:{httpServerPort}/{pngid} ，但 pngid 可以是任意值，可以将此值设置为一个随机数。这样就不需要刷新浏览器了。

**Comment by pandolia** [comment]
修改后的代码已经push上去了。

**Comment by huangzk** [comment]
嗯嗯，感谢。
