### ISSUE TITLE
sendto 报100012是什么问题？

### ISSUE THREAD

**Issue by wugui01** [pandolia/qqbot#136]
[ERROR] 第3次请求“http://d1.web2.qq.com/channel/send_bud
y_msg2”时出现 请求被拒绝错误, html='{"errmsg":"error!!!","retcode":100012}\n'

**Comment by pandolia** [comment]
应该是登录过期了。需要重新扫码登录

**Comment by wugui01** [comment]
谢谢，问题解决了
