### ISSUE TITLE
qqbot 可以定制成私聊每个都回复，群聊的话只有@才回复消息吗。

### ISSUE THREAD

**Issue by huangzk** [pandolia/qqbot#137]
@qqbotslot
def onQQMessage(bot, contact, member, content):

**Comment by pandolia** [comment]
可以的。 contact.ctype == 'buddy' 表示这是好友消息； contact.ctype == 'group' 表示这是一个群消息。 '@ME' in content 表示这是一个群消息且被 @ 了。

**Comment by huangzk** [comment]
好的,感谢

**Comment by pandolia** [comment]
可以看下不同类型的联系人的属性：
https://github.com/pandolia/qqbot/blob/master/qcontact-attr.md

**Comment by huangzk** [comment]
好的。上次说的那个二维码你把url改成跟pngid相关了，那我网页上展示二维码需要怎么弄呢。。。可以获取到二维码地址吗。。
