### ISSUE TITLE
邮箱收取二维码，查看邮件，扫描二维码，当二维码失效的时候，不能重新收到二维码邮件

### ISSUE THREAD

**Issue by wugui01** [pandolia/qqbot#139]
[WARNING] 查询邮箱 **********@qq.com 中的邮件失败 Please usi
ng authorized code to login. More information at http://service.mail.qq.com/cgi-
bin/help?subtype=1&&id=28&&no=1001256

**Comment by pandolia** [comment]
看这个错误信息，应该是授权码不对的原因。需要提供开通 smtp/imap 服务的授权码。可能你提供的是 smtp/pop3 服务的授权码。

**Comment by wugui01** [comment]
确实是添加的smtp/pop3 服务的授权码，已更新，谢谢
