### ISSUE TITLE
关于主动发送消息遇到的若干问题

### ISSUE THREAD

**Issue by rongzeng54** [pandolia/qqbot#141]
首先，非常感谢 @pandolia  的作品帮我们解决了问题。
切入正题，我们目前使用你的 qqbot 来做一些日常的定时通知，遇到了一些问题如下：
- 某些时候，会重复发送相同的消息，INFO日志并没有显示消息发送重复了
- 发送行数较多的消息，如8~9行，会自动进行非预期的截断
- 某些时候，会遇到[time] [ERROR] 第3次请求“http://d1.web2.qq.com/channel/send_qun_msg2”时出现 请求被拒绝错误, html='{"errmsg":"error!!!","retcode":1202}\n' 

再次感谢 @pandolia

**Comment by pandolia** [comment]
第1、3个问题和 QQ 服务器返回 1202 错误有关。当调用 webqq 发消息的接口发消息时， QQ 服务器可能返回 “代码0“ ，表示发消息成功，也可能返回 “代码1202” ，表示发消息可能失败（但其实大部分情况下都是发送成功的）。
bot.SendTo 接口中第三个参数为 resendOn1202 ，若此参数为 True （默认值），则发消息时如果 QQ 服务器返回代码 1202 ，还会继续发送 3 次，直至返回代码 0 ， 若此参数为 False ，则不会尝试重发。
所以你所提的1、3问题，都是因为设置了 resendOn1202 的原因。
如果将此参数设置为 False ，则不会出现 1、3 问题，缺点是，有时候消息没发送出去，但是仍然返回发送成功的信息。
总之因为这个 1202 代码的不确定性，没有完美的解决办法。请根据实际情况选择 resendOn1202 的值。

**Comment by pandolia** [comment]
至于非预期的截断，这是因为一条消息最多只能有约240个汉字或720个英文。如果消息内容超过了此长度，qqbot 会对消息进行分割后再发送出去。具体的原则是：

一次发消息内容最长为 240 个汉字或 720 个英文，也就是 utf8 编码后的长度不能超过 720 ，超过此长度将被分段，按以下原则分段：如果 620~720之间有空格字符（空格，\t，\n等），则按最后一个空格进行分割，否则，按 720 进行分割。

**Comment by pandolia** [comment]
如果以上分割原则不符合你的要求，你可以自行分割消息后再发送消息。

**Comment by pandolia** [comment]
如果你想用自己的分段函数，可以这样按以下方式覆盖 basicqsession.py 中的 Partition 函数：

    def myPartition(msg):
        return msg[:200], msg[200:]

    import qqbot.basicqsession; basicqsession.Partition=myPartition

默认的 Partition 函数定义在 common.py 中，代码如下：

     def isSpace(b):
        return b in [' ', '\t', '\n', '\r', 32, 9, 10, 13]
    
    def Partition(msg):
        if PY3:
            msg = msg.encode('utf8')
    
        n = 720
    
        if len(msg) < n:
            f, b = msg, b''
        else:
            for i in range(n-1, n-101, -1):
                if isSpace(msg[i]):
                    f, b = msg[:i], msg[i:]
                    break
            else:
                f, b = msg[:n], msg[n:]
        
        if PY3:
            return f.decode('utf8'), b.decode('utf8')
        else:
            return f, b

**Comment by rongzeng54** [comment]
感谢 @pandolia 的详细解答

**Comment by Lesita** [comment]
也有点其他问题，有空通过 mailing 再说。

使用Android版AquaMail发送
http://www.aqua-mail.com


在2017年5月8日 下午1:28:07 rongzeng <notifications@github.com>写道：
