### ISSUE TITLE
二维码服务器开启后，部署在服务器上，过一段时间二维码服务器的端口就停止监听了。

### ISSUE THREAD

**Issue by huangzk** [pandolia/qqbot#142]
这个二维码服务器如果不主动关闭，会自己结束端口吗。

**Comment by pandolia** [comment]
qqbot 进程结束时此服务器才会关闭。但是扫码后因为二维码图片被清除，所以扫码后再去打开二维码的 url 地址会出现 404 not found 的错误。

**Comment by huangzk** [comment]
扫码登陆成功后，清除二维码，如果过一段时间cookie过期了，qqbot进程是不是会自己关闭，需要手动重启？如果没有配置restartOnOffline:true的话。

**Comment by pandolia** [comment]
是的。
设置了 restartOnOffline 才会自动重启。
