### ISSUE TITLE
消息发不出去了

### ISSUE THREAD

**Issue by Ninzero** [pandolia/qqbot#144]
我和一个朋友开玩笑，写了个循环500次的发送代码……就是会把同一句话发送500次，然后发到一半就发不出去了……**尴尬尴尬**
错误代码是
`第3次请求“http://d1.web2.qq.com/channel/send_buddy_msg2”时出现 请求被拒绝错误, html='{"errmsg":"error!!!","retcode":1202}\n'`
不知道有没有解决办法？谢谢

**Comment by pandolia** [comment]
1202错误可以忽略，不影响的。或者在调用 SendTo 的时候将第三个参数设置为 False： 

    bot.SendTo(contact, content, resendOn1202=False)

不过连续对同一个人发信息很容易被封号或锁定。我以前试过发 10 多条信息就被锁定号码了。你居然可以发 200 多次。。。

**Comment by Ninzero** [comment]
不不不……这个“一半”不是确切的数量……大约发了几十条吧……那这种情况是永久性的吗？

**Comment by pandolia** [comment]
还能接收到消息那就还可以使用。但建议还是不要滥发消息。

**Comment by Ninzero** [comment]
好的，谢谢了

**Comment by pandolia** [comment]
不客气

**Comment by bugyak** [comment]
楼主被解封了吗？
