### ISSUE TITLE
异常停止（code=203）

### ISSUE THREAD

**Issue by msdx** [pandolia/qqbot#145]
```
[2017-05-07 14:16:05] [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, html='{"errmsg":"error","retcode":100001}'
[2017-05-07 14:16:05] [CRITICAL] QQBOT 异常停止（code=203）
```
这是啥原因呢？

**Comment by pandolia** [comment]
登录过期了，需要重新扫码登录

**Comment by shangguan1997** [comment]
只能登陆不到一个小时了？

**Comment by pandolia** [comment]
汗，我测试一下。

**Comment by msdx** [comment]
出现了一次，重启一下就好了

**Comment by shangguan1997** [comment]
我这边每次都是这样。。

**Comment by pandolia** [comment]
重启的时候需要重新扫码么？还是上次保存的 pickle 文件可以用？

**Comment by msdx** [comment]
不需要重新扫描，直接就可以了。
我除了重启，还关了电脑上登录的QQ

**Comment by pandolia** [comment]
哦。那这个错误可以直接忽略。你先手动改一下 basicqsession.py 中的第 197 行，改为：

    expectedCodes = (0, 100003, 100100, 1202, 100001)

**Comment by pandolia** [comment]
修改后的代码已经 push 到 git 了。

**Comment by msdx** [comment]
好的。

**Comment by pandolia** [comment]
直接忽略 100001 代码错误似乎也不行。我已经正常运行了 2 天了，然后就开始收不到消息了。。。

**Comment by pandolia** [comment]
今天晚上又出现了下面这个错误：

     [ERROR] 第3次请求“https://d1.web2.qq.com/channel/poll2”时出现 请求被拒绝错误, 
                  html='{"errmsg":"error","retcode":103}'

之后自动登录还是可以成功收发消息。看来还得把 103 加到这个 expectedCodes 里面去。。。

**Comment by pandolia** [comment]
经过一天的试验，发现现在 100001 代码不会出现了，但 103 代码又会偶尔出现，而且出现后的 cookie 并未过期。因此准备将 poll 方法中的  expectedCodes 改为：(0, 100003, 100100, 1202, 103) 。

**Comment by smartgang** [comment]
用最新的2.3.7版本，还是会出现这个问题
在两台电脑开了两个在跑，一个跑了几个小时，另一个跑了10几个小时，都出现这个报错
有一个多次尝试失败后就彻底挂了，要关掉重开
有一个出了几次这个报错，自动重连又好了
