### ISSUE TITLE
加群欢迎信息怎么添加？

### ISSUE THREAD

**Issue by n37r06u3** [pandolia/qqbot#146]
没看见相关的接口呢

**Comment by Lesita** [comment]
加群后的发送到群里第一次的那个信息是一个“手机QQ客户端”的一个实现。

来自我的华为手机

n37r06u3 <notifications@github.com>编写：

**Comment by pandolia** [comment]
没有这个接口，抱歉。 webqq 本身收不到新加群的消息。
之前的版本也尝试过不停的获取群列表、再对比旧的群列表来得到新加的群。但效果很差。webqq提供的获取群列表的接口非常不稳定，经常返回残缺的数据。
