### ISSUE TITLE
判断 qqbot 被别人 at 的时候出现的问题

### ISSUE THREAD

**Issue by WangYihang** [pandolia/qqbot#147]
您好 , 非常感谢您开发的这款 qqbot 机器人框架 , 我在使用的时候发现了一些问题 , 在使用 "被 at 自动回复" 的功能的时候 , 我发现有时候机器人并不能很好地去判断自己是不是被 at 了 , 就会出现被 at 了但是并没有判断成功 , 我找到了一个解决方案是 , 在判断是否被 at 的时候直接使用 : 
```
if '@username' in content:
```
而不是使用 : 
```
if '@ME' in content:
```
这样似乎更准确一些
可以首先获取 qqbot 的昵称 , 然后再进行判断 , 不知道我这样的做法是不是很合理...
再次感谢 , 这个框架真的非常好用

**Comment by pandolia** [comment]
这样也可以的，就是不太通用。不同的群中自己的群名片可能不一样，所以 '@username' 就不一定全部有效。
@ME 出问题是因为今天 QQ 又改接口了。。。我会尽快修复。

**Comment by WangYihang** [comment]
原来是QQ改接口了呀....我还就纳闷儿呢...为啥昨天晚上测试过的脚本今天就不行了...

**Comment by WangYihang** [comment]
辛苦了辛苦了 :100:

**Comment by pandolia** [comment]
v2.2.10版中的 @ME 判断比原来更加准确了。
