### ISSUE TITLE
关于发送消息的时候能否直接指定 QQ 号 或者 群号

### ISSUE THREAD

**Issue by WangYihang** [pandolia/qqbot#148]
请问 WebQQ 的协议中支持直接通过群号或者QQ号直接发送消息吗 ? 还是通过别的什么身份标识 ? 还是关于群里面 @ 的时候出现的问题 , 如果可以通过 @的那条消息获取消息发送者的QQ号 , 那么是不是就可以解决之前的群名片冲突的问题了

**Comment by pandolia** [comment]
WebQQ 协议是通过 uin 发消息的，uin每次登陆都要变。
消息发送者的 QQ 号可以在 onQQMessage 函数中通过 contact.qq 或 member.qq 得到，你再看看文档。

**Comment by WangYihang** [comment]
啊...抱歉抱歉...怪我是我没有仔细看过文档...不好意思啊...我去看看 , 谢谢你啦

**Comment by WangYihang** [comment]
诶...对了你说的文档指的是 README.md 吗

**Comment by pandolia** [comment]
是的。
注意有时候 contact.qq 或 member.qq 可能是 '#NULL' ，因为有可能存在获取不到联系人的 QQ 号的情况。
