### ISSUE TITLE
关于 Web 接口调用 qqbot 发送消息的安全性问题

### ISSUE THREAD

**Issue by WangYihang** [pandolia/qqbot#149]
您好 , 我还有一个问题是关于 Web 接口中调用 qqbot 发送消息的安全性问题 
我在本地测试的时候发现直接去请求 Web 接口中的命令就可以直接发送消息了 , 这里似乎并没有对发送请求者身份的认证
我现在的情况是这样 , 有两台服务器 , 一台服务器运行 qqbot , 另一台服务器会产生一些信息需要用 qqbot 发送出去 , 但是这些消息的产生是随机的 , 而且我希望消息的发送的实时性比较高
这种情况应该怎么处理 ? 
如何能保证 qqbot 的接口不被他人非法调用 ? 辛苦了

**Comment by pandolia** [comment]
web 接口只能通过本机 127.0.0.1 调用。需要靠用户自己保证本机不被他人使用。

**Comment by pandolia** [comment]
只要你运行 qqbot 的机器不被别人使用，那就是安全的。

**Comment by WangYihang** [comment]
哦哦哦...懂了 , 我看到默认的配置监听的网卡是空 ... 这会不会有什么问题 ...

**Comment by pandolia** [comment]
你看到的那个是指配置文件中的 httpServerIP 么？那个其实不是配置 web 接口的监听 IP 的。
web 接口的监听 IP 无法配置或更改，永远都是 127.0.0.1 。

**Comment by WangYihang** [comment]
哦哦哦...原来是这样 , 好的好的 , 谢谢你的耐心解答 , 加油 :+1:

**Comment by pandolia** [comment]
不客气。
