### ISSUE TITLE
readme文档书写与代码不匹配

### ISSUE THREAD

**Issue by ByCnck** [pandolia/qqbot#15]
当前文档内容为：二维码获取地址为 http://服务器 IP:8080/login
实际为：              二维码获取地址为 http://服务器 IP:8080/qqbot/login

**Comment by pandolia** [comment]
好，感谢提醒。

**Comment by ByCnck** [comment]
顺便问一句，当前登陆有效期貌似就一天左右，到期后必须重新扫码登陆，有办法让登陆一直有效吗？

**Comment by pandolia** [comment]
没办法，只能保持登陆状态1~2天。后面会增加掉线后自动将二维码图片发送到邮箱的功能。

**Comment by ByCnck** [comment]
赞！我当前是这样做的：用pm2启动qqbot，发现掉线了，手机登陆二维码页面，截图，手机qq选择截图扫描。如果发邮件的话更方便一些。
