### ISSUE TITLE
centos下ctrl+c无法退出控制台

### ISSUE THREAD

**Issue by lvsenlin** [pandolia/qqbot#152]
好像是从2.2.6开始的

**Comment by pandolia** [comment]
需要按两次。

**Comment by Lesita** [comment]
因为需要将全部的 thread 接受到这个信号，所以需要多次快速发送 SIGQUIT ，几次就可以了。

来自我的华为手机

lvsenlin <notifications@github.com>编写：

**Comment by pandolia** [comment]
这可能 python 的多线程程序的通病，子线程收到 SIGQUIT 后，并没有将此信号传递给主线程。

**Comment by lvsenlin** [comment]
我猜可能是我的centos出问题了，tail命令也出同样问题了
