### ISSUE TITLE
大于号小于号问题

### ISSUE THREAD

**Issue by xuefer** [pandolia/qqbot#154]
别人发 < > &lt; &gt; 我在网页上收到的是 &lt; &gt; &lt; &gt;
我在网页发 < > &t; &gt; 别人在电脑/安卓上收到的是 &lt; &gt; &lt; &gt;

这个似乎是接口问题了, 为了机器人能收到 < >, 可以做替换, 但是想要发 < > 就没办法了

**Comment by pandolia** [comment]
没有办法发送大于号和小于号，例如：若使用 qq send buddy jack ">" ，那么对方收到的是 \&gt\; 。
