### ISSUE TITLE
python2.7 导入qqbot模块出现了问题

### ISSUE THREAD

**Issue by ylc395** [pandolia/qqbot#159]
已通过`sudo pip install qqbot`正确安装，命令行可以正常使用`qqbot`与`qq`指令，但想对其进行编程则出现无法导入的问题

![image](https://cloud.githubusercontent.com/assets/12264626/26286528/795f877e-3e9a-11e7-8925-1b2af1afb29b.png)

**Comment by pandolia** [comment]
你的 py 文件或文件夹的名字不能为 “qqbot” ，也不能为其他库的名称（比如： "string", "sys", ...）。
