### ISSUE TITLE
收到自己发送的消息

### ISSUE THREAD

**Issue by xuefer** [pandolia/qqbot#160]
似乎今天开始
群聊会收到自己发送的消息. 但是 onQQMessage 的群成员数据 qq == "#NULL", name == "#uinxxxxx"

**Comment by pandolia** [comment]
已经 push 了一个 commit 到 github，可以获取到自己发送的群消息了。而且不会引起额外的群成员列表更新。

**Comment by pandolia** [comment]
此时 onQQMessage 的群成员数据 qq 就是自己的 qq 号码。

**Comment by sjdy521** [comment]
是怎么区分其他设备上自己发送的消息的 因为在我看来和群里其他人发送的消息格式完全一样，根本区分不来

**Comment by pandolia** [comment]
在 onqqmessage 函数中，如果 member.qq == bot.conf.qq 那就是自己发的消息。

**Comment by pandolia** [comment]
底层判断原则：收到信息时，查找群成员列表中是否含有此信息的发送者的uin，如果查找不到，就做一次群成员列表更新，如果更新成功了还是查找不到，那就认为这是自己发的。理论上还是存在误判的可能，因为不确定webqq协议中是否还有别的可能。目前使用来看还是没什么问题。

**Comment by sjdy521** [comment]
好像现在又收不到其他设备自己发送的消息了 昙花一现的感觉…

**Comment by xuefer** [comment]
现在测试还是可以的. 自己发的或者别的设备发的都可以

**Comment by sjdy521** [comment]
我自己的帐号昨晚可以，现在就收不到任何自己发的消息了，好诡异，难道还是区别帐号的……

**Comment by pandolia** [comment]
我也还能收到。

**Comment by pandolia** [comment]
不过我也感觉这个功能可能很快又会被去掉。就像前几天的 “可以直接获取联系人实际 QQ ” 的功能一样。

**Comment by xuefer** [comment]
到现在依然可以收到. 不过似乎应该看看能否换个方式检测自己的临时 uid, 现在收到群系统消息(生日提醒)的时候也会当做自己发的消息

**Comment by pandolia** [comment]
收到群系统消息(生日提醒)的具体格式是怎样的？可以先根据消息内容判断一下，如果满足某种格式就认为是系统消息。
