### ISSUE TITLE
通过HTTP API 接口发送表情

### ISSUE THREAD

**Issue by AwalkZY** [pandolia/qqbot#163]
请问如果要通过通过HTTP API 接口发送表情的话，应该怎么把表情加入？

**Comment by pandolia** [comment]
先进行 url 编码（ utf8 ）再发送，比如 /微笑 编码为 %2F%E5%BE%AE%E7%AC%91
http://127.0.0.1:8188/send/buddy/Eva/%2F%E5%BE%AE%E7%AC%91
