### ISSUE TITLE
能否提供一个用于监听"登录过期"的回调接口

### ISSUE THREAD

**Issue by brucezz** [pandolia/qqbot#165]
现在大概两天帐号就会登录过期一次，能不能提供一个回调接口，我通过注册一个函数，然后能监听到这个“登录过期”的信号，方便我执行一些额外的代码。

例如：

```python
@session_expired
def expired():
    notify_user() # 用户自定义的一些操作
```

**Comment by pandolia** [comment]
可以的。

**Comment by brucezz** [comment]
@pandolia  更新了麻烦告诉我一下 :)

**Comment by pandolia** [comment]
add-events 分支已增加 onExpire 事件，见：
https://github.com/pandolia/qqbot/tree/add-events
https://github.com/pandolia/qqbot/tree/add-events#%E5%85%AD-%E6%B3%A8%E5%86%8C%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0%E8%A2%AB%E4%BB%96%E4%BA%BA--%E7%9A%84%E9%80%9A%E7%9F%A5%E5%AE%9A%E5%88%B6%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1

**Comment by brucezz** [comment]
pypl 上最新的版本已经支持这个 feature 了吗

**Comment by pandolia** [comment]
还没有merge到master，你可以下载 add-events 分支的代码安装

**Comment by brucezz** [comment]
ok

**Comment by pandolia** [comment]
已经上传到 pip 了。

**Comment by pandolia** [comment]
@brucezz v2.3.2版中， onExpire 扩充为 onExit 函数，在 QQBot 停止、重启、登录过期、未知错误时被调用。原 onExpire 被删除。详见：
https://github.com/pandolia/qqbot/blob/master/qqbot/plugins/sampleslots.py#L60-L86

**Comment by brucezz** [comment]
ok
