### ISSUE TITLE
列表更新 事件

### ISSUE THREAD

**Issue by xuefer** [pandolia/qqbot#166]
1. 设置定期更新列表 (可以考虑加这个)
2. 收到群成员发消息 发现成员 无qq号信息时更新 (但要因为某些不可能获取到的而避免频繁反复获取)
新成员入群后, 列表里没有该成员信息的

关于问题2: 想要个"列表更新"事件/回调

**Comment by pandolia** [comment]
目前的更新机制基本上就是第2点说的那样。
关于第1点，自动定时更新可以由用户通过注册interval函数实现。2.1版中是有自动更新机制，但是由于webqq 的获取联系人列表的接口很不稳定，经常出错，所以 2.2 版就去掉了。

**Comment by xuefer** [comment]
非常感谢解释, 那我的问题改了, 换成需要在更新的时候收到事件. 因为我的比较复杂做了一些映射/记录之类, 再更新之后需要进一步同步这个映射/记录

**Comment by pandolia** [comment]
add-events 分支已增加列表更新事件，见：
https://github.com/pandolia/qqbot/tree/add-events
https://github.com/pandolia/qqbot/tree/add-events#%E5%85%AD-%E6%B3%A8%E5%86%8C%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0%E8%A2%AB%E4%BB%96%E4%BA%BA--%E7%9A%84%E9%80%9A%E7%9F%A5%E5%AE%9A%E5%88%B6%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1
