### ISSUE TITLE
无法在vps上运行qqbot

### ISSUE THREAD

**Issue by Ninzero** [pandolia/qqbot#167]
试着在自己的vps上跑了一下qqbot，发现会报错：
`Traceback (most recent call last):
  File "/usr/local/bin/qqbot", line 11, in <module>
    sys.exit(RunBot())
  File "/usr/local/lib/python3.5/dist-packages/qqbot/qqbotcls.py", line 82, in RunBot
    runBot((botCls or QQBot), qq, user)
  File "/usr/local/lib/python3.5/dist-packages/qqbot/qqbotcls.py", line 44, in runBot
    conf = QConf(qq, user)
  File "/usr/local/lib/python3.5/dist-packages/qqbot/qconf.py", line 195, in __init__
    self.readConfFile()
  File "/usr/local/lib/python3.5/dist-packages/qqbot/qconf.py", line 327, in readConfFile
    PRINT('\u672a\u627e\u5230\u914d\u7f6e\u6587\u4ef6\u201c%s\u201d\uff0c\u5c06\u4f7f\u7528\u9ed8\u8ba4\u914d\u7f6e' % strConfPath)
  File "/usr/local/lib/python3.5/dist-packages/qqbot/utf8logger.py", line 85, in PRINT
    utf8Stdout.write(s+end)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)`

看了一下似乎是编码问题，但具体为什么没有理解。

**Comment by pandolia** [comment]
什么系统？

**Comment by pandolia** [comment]
是不是以 root 用户运行的？

**Comment by pandolia** [comment]
你试试运行 sys.stdout.write('\u672a\u627e\u5230\u914d\u7f6e\u6587\u4ef6\u201c%s\u201d\uff0c\u5c06\u4f7f\u7528\u9ed8\u8ba4\u914d\u7f6e') ，能不能成功。

**Comment by Ninzero** [comment]
1、Ubuntu 16 (64bit)
2、是的
3、能得（至少没有报错）

**Comment by Ninzero** [comment]
最后一个命令是在vps上运行对吧

**Comment by pandolia** [comment]
输出结果是： **未找到配置文件“%s”，将使用默认配置** ？
换普通用户试试呢？

**Comment by pandolia** [comment]
你试试在你的 vps 上用 python3.5 运行下面的语句，看能否正常运行

import os, sys
bench = os.path.abspath(os.path.join(os.path.expanduser('~'), '.qqbot-tmp'))
p = os.path.join(bench, 'v2.2.conf')
sys.stdout.write('\u672a\u627e\u5230\u914d\u7f6e\u6587\u4ef6\u201c%s\u201d\uff0c\u5c06\u4f7f\u7528\u9ed8\u8ba4\u914d\u7f6e' % p)

**Comment by pandolia** [comment]
搜到一篇文章： https://www.binss.me/blog/solve-problem-of-python3-raise-unicodeencodeerror-when-print-utf8-string/
应该是因为 sys.stdout.encoding 是 'ANSI_X3.4-1968' 的原因，普通用户下这个值应该是 'utf8' ，没这个问题。

将 utf8logger.py 中的第 43 行改为：

    utf8Stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

应该就可以解决这个问题了。

**Comment by Ninzero** [comment]
好的，问题解决了，非常感谢

**Comment by pandolia** [comment]
用哪种方法解决的？

**Comment by Ninzero** [comment]
就是将utf8logger.py的第43行换掉了。

**Comment by Ninzero** [comment]
实在不好意思再问一句，因为我刚刚开始用vps不太懂，现在我用ssh远程控制vps运行qqbot，但是我只要把我这里的ssh窗口关掉，qqbot就不运作了，有没有办法可以让qqbot在服务器上自己运行？多谢多谢

**Comment by pandolia** [comment]
http://www.tennfy.com/1297.html

**Comment by Ninzero** [comment]
明白了，非常感谢
