### ISSUE TITLE
升级到2.2.18版后群的QQ为#NULL

### ISSUE THREAD

**Issue by chenhouwu** [pandolia/qqbot#169]
在升级到2.2.18后
当contact为group时，contact.qq的值为#NULL
这个问题在之前的版本（2.2.14？不确定）是不存在的，
之前我可以根据contact.qq判断是哪一个群

**Comment by pandolia** [comment]
昨天都没这个问题，估计是又改协议了。。。

**Comment by pandolia** [comment]
测试了一下，这个接口已经废了：
http://qun.qq.com/cgi-bin/qun_mgr/get_group_list
原来可以返回所有群的资料，现在只能返回有管理权限的群的资料，因此导致这些群的实际 QQ 都获取不到了，进而导致这些群的成员的实际 QQ 也获取不到了。

**Comment by chenhouwu** [comment]
腾讯啊腾讯，说什么好呢。。。。

**Comment by pandolia** [comment]
暂时只能手工绑定群QQ了。
下载 https://raw.githubusercontent.com/pandolia/qqbot/add-events/qqbot/qcontactdb/fetch.py ，替换原来的 qqbot/qcontactdb/fetch.py 。
再在工作目录（就是配置文件所在的目录）下新建一个“groupqq”文件，输入：

    12345,xxx
    23233,yyy

每行第一个数字为群 QQ ，之后是逗号，最后是群名称。不要添加空格。文件保存为 utf8 编码。

如果有 6 月 7 日之前的联系人数据库 db 文件，可以从这个 db 文件里导出这些数据，下载： https://github.com/pandolia/qqbot/blob/add-events/qqbot/qcontactdb/getgroupqq.py 文件，并运行 python getgroup.py xxx.db 可以自动生成一个这样的文件 groupqq 。

**Comment by chenhouwu** [comment]
哦。。才看到你的说明，
我也是这么干的，群不多，就直接在代码里加了个群名到群qq的字典。

**Comment by xuefer** [comment]
又恢复了的样子
