### ISSUE TITLE
关于定时任务

### ISSUE THREAD

**Issue by pinkomeo** [pandolia/qqbot#17]
楼主你好~

python小白一枚
想问一下 如果我想让机器人每天定时发送消息到某个群
这个时间控制我应该加到哪里呢？

找到了一个就是循环查询登录状态的那里 不知道对不对 好像也没成功 T-T

**Comment by pandolia** [comment]
重载 onPullComplete 方法就可以了。该方法会不停的被 Run 方法调用，一般每隔2分钟被调用一次（无消息的情况下）。需要定时发送消息到群的话，可以参考下面这段代码：

    class MyQQBot(QQBot):
        timeout = 0
        def onPollComplete(self, msgType, from_uin, buddy_uin, message):
            if time.time() >= self.timeout:
                uin = self.groupsDictQ[**你的群的qq号**]['uin']
                self.send('group', uin, **你的消息**)
                self.timeout = time.time() + **你的时间间隔**
