### ISSUE TITLE
可以部署在VPS上吗？

### ISSUE THREAD

**Issue by zhuxiaole** [pandolia/qqbot#172]
请问VPS linux上是否可以弹出二维码？

**Comment by pandolia** [comment]
没有桌面环境不能弹出。可以使用 邮箱模式  、 服务器模式 或 文本模式 来显示二维码。最简单的，可以用 文本模式，但需要先安装 pillow ：

    sudo pip install pillow
    qqbot -cq

**Comment by zhuxiaole** [comment]
3Q啦！
