### ISSUE TITLE
关于群好友的获取

### ISSUE THREAD

**Issue by pinkomeo** [pandolia/qqbot#18]
现在好像是只获取了群列表。群里的人是否可以获取呢？

**Comment by pandolia** [comment]
暂时还没有这个功能，稍等两天，我会增加相关的代码。

**Comment by pinkomeo** [comment]
谢谢！我正在改代码这两天，，

主要的问题是：
1.感觉现在获取好友有的时候成功但是获取的好友数量为0，手动refetch有时候也是0，不知道是不是那边服务器的问题
2.群里的人的获取，您正在添加。主要是想针对不同的人的@然后回复给他@


感谢一直维护 么么哒

**Comment by pandolia** [comment]
您好，最新版的已经增加获取群内成员的功能。

**Comment by pinkomeo** [comment]
好的 我今天再学习一下！谢谢
