### ISSUE TITLE
发现可以使用网易imap的方法

### ISSUE THREAD

**Issue by shadowsong91** [pandolia/qqbot#183]
imap.send('%s ID ("name" "qqbot" "version" "1.0" "vendor" "qqbot")\r\n' % imap._new_tag())
在`login`之后调用。
客服的回答是需要添加id，然后搜了一下ID的用法。亲测可用。

**Comment by pandolia** [comment]
这是干吗的？

**Comment by pandolia** [comment]
登录之后给自己发一封邮件？

**Comment by shadowsong91** [comment]
一个名为`ID`的指令，和`SELECT`这些指令一起定义在RFC文档中的。当时查的原文忘记保存了。你可以先试一下。

**Comment by pandolia** [comment]
抱歉，我还是没理解这行代码的具体作用？是用来发送二维码邮件的吗？

**Comment by pandolia** [comment]
为什么要发送id指令呢？

**Comment by shadowsong91** [comment]
之前在我使用python调用网易IMAP的时候，所有的操作都会失败，如`SELECT`，网易客服的回答是缺少了`IMPA ID`，然后我在`imap.login`之后，接着调用上面说的`imap.send`这个方法，后面的操作都正常了。网易的邮箱多了一些验证步骤。不知道我说明白了没有。

**Comment by pandolia** [comment]
明白了，感谢感谢。我按您的方法试一下。

**Comment by pandolia** [comment]
我还以为是因为网易邮箱不支持imap协议的原因。

**Comment by shadowsong91** [comment]
网易貌似没有把这个公布，这个就比较过分了，估计是为了强推邮箱大师。您可以先写一个demo试试，看看能否正常查询。

**Comment by yoker** [comment]
ID 指令是表明自己身份的。网易对自实现邮件客户端的情况下，对这个指令做了强制要求。

**Comment by shadowsong91** [comment]
应该是这样，调用之后，一切都正常了。

**Comment by pandolia** [comment]
测试了一下，按以上方法登录成功后，下面两条命令可以运行：

    imap.select('INBOX')
    imap.search(None, '(UNSEEN)')

但当我想取得某个邮件的主题时，运行下面的命令出错了：

    imap.fetch(email_id, 'BODY.PEEK[HEADER.FIELDS (SUBJECT)]')   # email_id 为邮件的 id ，比如： '0'

不知道是不是网易邮箱不支持 PEEK 指令。

**Comment by pandolia** [comment]
发邮件是没问题的。就是查询邮件时出错了。

**Comment by pandolia** [comment]
搞定了，原来是 fetch 函数里面的命令要加括号的原因，改成下面这样就没问题了：

    imap.fetch(email_id, '(BODY.PEEK[HEADER.FIELDS (SUBJECT)])')

QQ邮箱不需要加这个括号的，其实也没必要加，网易好像就是要搞得和别家不一样似的。

**Comment by pandolia** [comment]
已在 v2.3.5 版中增加网易邮箱的支持，再次感谢 @shadowsong91 。

**Comment by shadowsong91** [comment]
恭喜！
