### ISSUE TITLE
接收消息出现截断和空的现象

### ISSUE THREAD

**Issue by redrum0003** [pandolia/qqbot#184]
这两天发现，一些比较长的消息会出现两种情况：
1. 图文消息，来自群，消息会出现截断的情况。从客户端上查看消息是完整的，但是 qqbot 的 INFO 显示消息不完整。
2. 文字消息，来自好友，超出一定字数，INFO 显示收到消息 ""
===========================
以下消息会出现空的情况
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
——————————
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六abc
===========================
以下消息能正常接收
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
——————————
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六七八九十
一二三四五六ab
===========================

qqbot 版本 2.3
python 版本 2.7.12
ubuntu 16.04

**Comment by pandolia** [comment]
测试了一下，用 PC 客户端发的 第一段消息 是可以正常收到的，发送 第一段消息x2 时，会收到两条分段的消息：

[2017-07-12 17:15:15] [INFO] 来自 群“connie”[成员“Eva”] 的消息: "一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五
六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十——————————一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六abc一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七
八九十一二三四五六七八九十一二三四五六七八"
[2017-07-12 17:15:19] [INFO] 来自 群“connie”[成员“Eva”] 的消息: "九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三
四五六七八九十——————————一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六abc"

**Comment by pandolia** [comment]
不过回车符全部被过滤掉了。

**Comment by pandolia** [comment]
可能跟发送消息的客户端也有关系。

**Comment by pandolia** [comment]
Mac 版的 QQ 发的消息中的回车符不会被过滤。
