### ISSUE TITLE
群发群消息出现有几个群发送不了

### ISSUE THREAD

**Issue by chengshuyi** [pandolia/qqbot#185]
在输出显示是所有的群都已经发送了消息，但是用手机看的话，有几个群看不到我发的消息。我的是一共群发到13个群，有4个群接收不到，如果再继续使用的话，就会出现安全模式，让我修改密码。

**Comment by chengshuyi** [comment]
现在又接到下线通知了，这个应该如何解决？

**Comment by pandolia** [comment]
群发是很容易被封号的，只能是增加发送间隔时间，另外需要用一个注册时间久一点、比较活跃的号码。
