### ISSUE TITLE
您好，我准备挂在树莓派上使用

### ISSUE THREAD

**Issue by sandorZHAO** [pandolia/qqbot#187]
可是发现了个
[error]无法开启qqbot-term 服务器 errno98 address already in use
[error] qq命令和HTTP-API 接口将无法使用

这样的问题，127.1被占了？
谢谢作者！

**Comment by pandolia** [comment]
是的，你这个是同时开了两个qqbot进程吧，需要为每个进程设置单独的端口号。具体请看文档中关于配置的用法。
