### ISSUE TITLE
TermBot只支持GET

### ISSUE THREAD

**Issue by wujiyu115** [pandolia/qqbot#188]
TermBot 现在只支持GET,请求来接收命令。我是想来游戏服的报错信息然后Post给TermBot ,数据量可能比较大, 不想再多开一个端口来自己做监听,
而且QTermServer绑定 的ip是127.0.0.1,局域网无法访问,0.0.0.0或者空才行

**Comment by pandolia** [comment]
可以看看 termbot.py 里面的 onTermCommand ，还有 mysocketserver.py ，根据你的需要修改这些的代码。

**Comment by pandolia** [comment]
termbot 的 GET 一次可以接收 8096 个字节，还不够么？

**Comment by pandolia** [comment]
还可以看一下 qqbot.plugins.addqqcmd 插件的代码，这个插件介绍了如何增加自定义 qq 命令的方法

**Comment by wujiyu115** [comment]
现在是把qqbot当然一个组件使用,没去修改源码,换了另外一种方式。再起一个端口做监听.再用qqbot的http-api接口请求数据,8096个字节不够,重启的输出太多了
