### ISSUE TITLE
b.uin : str 对象，好友的 uin ，每次登录时分配的一个随机 id 对于一个好友来说，这个值是不是固定的？

### ISSUE THREAD

**Issue by bugyak** [pandolia/qqbot#189]
因为我的机器人开启了可以任何人添加好友，也就是说，存在大量单向好友关系
即 他们的好友列表中有机器人
而 机器人好友列表中没他们
也就获取不到 QQ 号码
因此需要同过 uin 来识别一个帐号
如果每次 qq start 登录的话 uin 都变化，可能就无法进行绑定了
请问 这个 uin 会变化吗？

**Comment by pandolia** [comment]
每次登录 uin 都会变化。这是腾讯的设置。

**Comment by pandolia** [comment]
可以用昵称或备注名绑定啊

**Comment by bugyak** [comment]
@pandolia 好像没有接口设置备注～

**Comment by pandolia** [comment]
哦，是的，webqq是没这个接口。用昵称总是可以的。
