### ISSUE TITLE
修改文档中 qqbotsched 的 day_of_week 参数说明， 0 代表周一， 6 代表周日。

### ISSUE THREAD

**Issue by leeyisoft** [pandolia/qqbot#190]
day_of_week 参数 为什么不0代表周日，1代表周一 ... 6代表周六

**Comment by pandolia** [comment]
额， apscheduler 库中就是这么设定的，确实很蛋疼。

**Comment by leeyisoft** [comment]
那么，为啥我们这里不这么设置呢？

**Comment by pandolia** [comment]
跟 apscheduler 库统一啊，用的都是他的接口，没道理用不同的参数啊。
