### ISSUE TITLE
使用qqblt登录的QQ号被永久冻结

### ISSUE THREAD

**Issue by MinezzZ** [pandolia/qqbot#192]
通过命令行打开qqbot扫码登录之后，重新打开一个命令行发送一个消息给另一个QQ，然后在电脑和手机登陆的QQ就被踢下线，再上就提示永久冻结了。不知道是为什么，望告知。

**Comment by pandolia** [comment]
可能是消息内容有敏感词。或者发消息太频繁了。

**Comment by ttionya** [comment]
我今天遇到了和你一样的情况，也是用命令行发送一个消息给另一个QQ，之后立刻电脑和手机登录的QQ就被踢下线，永久冻结，无法申诉。账号是昨天晚上用手机号注册的，存活时间不超过18小时。

所以应该不是敏感词，因为我测试发送表情 /doge，表情无法被格式化成正常表情，只是以文本格式输出，消息也不是过于频繁。

**Comment by kaiattrib** [comment]
我之前也是各种冻结，因为我是做状态回应，我想是系统检测到响应太快且每次内容相似。后面我的解决办法是sleep2秒，每次随机插入随机长度的几个汉字在前面，就没有被冻结了。

**Comment by tiamit** [comment]
最主要的就是要绕过这个机器人检测，所以机器人的特征不能有。
我的建议就是随机延时发送，然后发送相似的内容的时候，加一些随机的表情符号穿插在其中。
-------------------------------------------------------------
Like


邮箱：mengli721014@163.com

在2018年06月05 19时03分, "Ken Chan"<notifications@github.com>写道:

我之前也是各种冻结，因为我是做状态回应，我想是系统检测到响应太快且每次内容相似。后面我的解决办法是sleep2秒，每次随机插入随机长度的几个汉字在前面，就没有被冻结了。
