### ISSUE TITLE
非常难用 能不能把配置塞在Login参数里面 或者 自定义配置路径

### ISSUE THREAD

**Issue by 631068264** [pandolia/qqbot#196]
RT

**Comment by pandolia** [comment]
你说的这两个功能都有。自己看文档吧。

**Comment by 631068264** [comment]
你的文档只有README.md吗？跪求其他文档。我看完两三遍没找到。如果真的没有其他的，我建议你看看你自己写的文档。qq机器人就你写的比较正常，帮帮忙。

**Comment by pandolia** [comment]
自定义配置路径：https://github.com/pandolia/qqbot#%E5%B7%A5%E4%BD%9C%E7%9B%AE%E5%BD%95

**Comment by pandolia** [comment]
用 qqbot -b /my/path 启动，可以把配置路径切换到 /my/path

**Comment by pandolia** [comment]
bot.Login 方法的参数就是命令行参数，比如： bot.Login(['-q', '1234', '--debug']) 等。不过你可能需要先运行 qqbot --help ，看一下命令行参数的格式。另外还需要看一下文档第七节关于配置文件和配置参数的用法。
