### ISSUE TITLE
如何指定一个qq号发消息？

### ISSUE THREAD

**Issue by huxiaoqian** [pandolia/qqbot#199]
作者你好，我同时在一台服务器上运行多个qqBot进程（分别登录了不同的qq号），然后发送消息的时候如何指定其中一个qq号发送消息而不需要重新扫码呢？

**Comment by pandolia** [comment]
不同的 qqbot 进程设置不同的端口号 termServerPort ，再通过端口号发消息，比如：

     # 第 1 个终端，第 1 个 qqbot 进程，端口号 8188
     >>  qqbot -p 8188

     # 第 2 个终端，第 2 个 qqbot 进程，端口号 8189
     >>  qqbot -p 8189

     # 第 3 个终端
    >> qq 8188 send buddy xxx hello   # 利用第 1 个 qqbot 发消息
    >> qq 8189 send buddy xxx hello   # 利用第 2 个 qqbot 发消息

有关 termServerPort 的设置详见：
https://github.com/pandolia/qqbot#qqbot-term-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7-termserverport-
