### ISSUE TITLE
登录成功获取列表之后，请求错误。

### ISSUE THREAD

**Issue by MayneYao** [pandolia/qqbot#20]
`[2016-12-13 12:09:31] [CRITICAL] 第5次请求“https://d1.web2.qq.com/channel/poll2”时出现“网络错误或url地址错误”，终止 QQBot`

换机器试了下一样的情况。

我注意过这里的代码。
`
            # 若 retcode 有误，一般连续 3 次都出错就没必要再试了 (j <= 2)
            if i <= 4 and j <= repeatOnDeny:
                DEBUG('第%d次请求“%s”时出现“%s”, html:\n%s',
                      i+j, url, errorInfo, html)
`
上个版本是6。也会报相同的错误。第7次请求xxxxxx 然后终止。是协议的问题吗=。=

**Comment by pandolia** [comment]
您运行的时候用 -d 打开 debug 试试，看看有什么输出内容。

**Comment by pandolia** [comment]
您用的是最新的 1.9.3 版吗？我刚才试了一下，没出现问题。

也有可能 smartqq 协议又小改了一下，您先试试把这里改成这样，看看有没有用：

            except (requests.ConnectionError, ValueError):
                if url == 'https://d1.web2.qq.com/channel/poll2':
                    continue
                i += 1
                errorInfo = '网络错误或url地址错误'
