### ISSUE TITLE
关于之前永久冻结的反馈

### ISSUE THREAD

**Issue by MinezzZ** [pandolia/qqbot#201]
之前反馈过一次，地址https://github.com/pandolia/qqbot/issues/192
不好意思反馈之后忘了，以为有邮件提醒发现没提醒，实在不好意思。
我看了另一个朋友的反馈，也是差不多。应该不是发送消息太频繁或者包含敏感词语，我发的是“你好”，只发了一遍。
那个QQ也是当天申请的，可能是这个原因，特地跟你反馈一下。

**Comment by onlinehack** [comment]
刚才就测试了下plugin下面的 sample插件 也被永久封停了一个qq

**Comment by MoseChan** [comment]
我也是被冻结了 o.O

**Comment by pandolia** [comment]
我的号偶尔发发消息，一般没有封停，可能是注册时间比较长。

**Comment by MoseChan** [comment]
我的号也注册了的时间也不短(两年不知道短不短)
算了，反正那个号也没啥用。 0.0

**Comment by duchenpaul** [comment]
我的小号使用半天被冻结了，后解锁，每个小时给我大号发一条信息不算频繁吧？ 现在还在发，看看什么时候再次冻结，小号闲置n年。
