### ISSUE TITLE
qqbot 能否获取自己好友的性别和年龄

### ISSUE THREAD

**Issue by leeyisoft** [pandolia/qqbot#203]
如title，qqbot 能否获取自己好友的性别和年龄？如果能够的话，代码要怎么写呢？

**Comment by pandolia** [comment]
这个，暂时没这个功能。

**Comment by leeyisoft** [comment]
大神，如果以后可以“获取自己好友的性别和年龄”的话，通知一下我，或者在这个后面添加一条回复😁 @pandolia

**Comment by pandolia** [comment]
好的。
