### ISSUE TITLE
“判断是否是自己发的消息”中，member.uin与本次登录的qq号不一致

### ISSUE THREAD

**Issue by Nugine** [pandolia/qqbot#204]
qqbot接收到自身在群里发的消息，但member.uin与本次登录的qq号不同。uin与qq号应该不可能相同。
如果自身发送的消息可以被处理并回应，则有可能引起循环。
那么如何判断是否是自己发的消息？

**Comment by pandolia** [comment]
“uin与qq号应该不可能相同” 这个结论怎么得出来的？

**Comment by pandolia** [comment]
如何判断自己发的消息：https://github.com/pandolia/qqbot#%E5%88%A4%E6%96%AD%E6%98%AF%E5%90%A6%E6%98%AF%E8%87%AA%E5%B7%B1%E5%8F%91%E7%9A%84%E6%B6%88%E6%81%AF

**Comment by Nugine** [comment]
以下是代码片段：
```
    elif content == '-test':
        answer = '''time:{};\ncontact.uin:{};\nmember.uin:{};\ncontent:{}'''
        answer = answer.format(datetime.now(), contact.uin, member.uin if not member == None else None, content)
        bot.SendTo(contact, answer)
    elif content == 'your qq':
        bot.SendTo(contact, bot.conf.qq)
    elif 'loop' in content:
        answer = '''time:{};\ncontact.uin:{};\nmember.uin:{};\ncontent:{}'''
        answer = answer.format(datetime.now(), contact.uin, member.uin if not member == None else None, content)
        bot.SendTo(contact, answer)
```
![beh1i4 abqq4 5 qh f b](https://user-images.githubusercontent.com/30099658/29926244-71b038ca-8e95-11e7-8519-433d0bf066b9.png)
[图1]
![xozi j39d s 408 x7d](https://user-images.githubusercontent.com/30099658/29926248-76530678-8e95-11e7-82bf-aa617c9de767.png)
[图2]
![m 4im1bt l _ jd13t dp7](https://user-images.githubusercontent.com/30099658/29926250-78f8e636-8e95-11e7-8117-011ee480128e.png)
[图3]

图1中显示bot.conf.qq为2414122758。
图2中显示正常的回复。
图3中，回复变得不正常，因为 'loop' in content 对于自身发出的消息仍然成立，这就引起了循环。
不正常回复中的member.uin为901975197，与qq号2414122758不相同。
uin是一个临时唯一码，会随时间变化，所以应该不可能和qq号相同。

**Comment by pandolia** [comment]
你还是测试一下我发的链接里面的代码，再来下结论吧。

**Comment by pandolia** [comment]
用 new object 发同样的消息，再试一下

**Comment by pandolia** [comment]
用 new object 发同样的消息，再试一下

**Comment by pandolia** [comment]
你截屏的记录中，发送 your qq 这些消息的人，并不是qqbot本次登录的用户。

**Comment by pandolia** [comment]
你截屏的记录中，发送 your qq 这些消息的人，并不是qqbot本次登录的用户。

**Comment by pandolia** [comment]
所谓 自己发的消息 ，指的是本QQ号发的消息

**Comment by pandolia** [comment]
用你的 new object 发送-test ，看回复内容中的 member.uin 是否是 new object 的qq。

**Comment by pandolia** [comment]
不过图3是有些奇怪

**Comment by pandolia** [comment]
用 new object 发送-test 的结果是对的么？

**Comment by Nugine** [comment]
测试结果：
![1 1](https://user-images.githubusercontent.com/30099658/29967906-8e4ba076-8f4b-11e7-823c-7d8c003b438b.png)
![1 2](https://user-images.githubusercontent.com/30099658/29967905-8e4b9202-8f4b-11e7-95d6-14951d79d353.png)
![1 3](https://user-images.githubusercontent.com/30099658/29967904-8e497102-8f4b-11e7-8688-d668fc365c33.png)
![1 4](https://user-images.githubusercontent.com/30099658/29967907-8e53e948-8f4b-11e7-8d1c-2c4d766d1845.png)
![1 5](https://user-images.githubusercontent.com/30099658/29967903-8e475930-8f4b-11e7-8007-672bc070c7ad.png)
我再用示例代码试试看。。。

**Comment by Nugine** [comment]
isMe.py代码：
```Python
# coding=utf8
# from qqbot.utf8logger import INFO
def onQQMessage(bot, contact, member, content):
    if getattr(member, 'uin', None) == bot.conf.qq:  # 注意：不要使用 member.uin
        bot.SendTo(contact, '是我说的！')
    else:
        bot.SendTo(contact, '不是我说的！')
```
测试结果：
![ri8m o0at gc 0vnr4v l](https://user-images.githubusercontent.com/30099658/29968450-575b320e-8f4e-11e7-8565-f1fb572fb38a.png)

无限循环。。。

**Comment by pandolia** [comment]
能否发一下 qqbot 控制台显示的 log ？

**Comment by Nugine** [comment]
![default](https://user-images.githubusercontent.com/30099658/29970917-0fbcfb70-8f59-11e7-89de-191f312c06c4.PNG)
![1](https://user-images.githubusercontent.com/30099658/29970920-104a2a7c-8f59-11e7-9d93-58151452ee72.PNG)
![2](https://user-images.githubusercontent.com/30099658/29970923-119001f4-8f59-11e7-88b8-8942cf4d9a9a.PNG)
![3](https://user-images.githubusercontent.com/30099658/29970926-12810e3c-8f59-11e7-89db-b73e356363b5.PNG)

**Comment by pandolia** [comment]
哦，这是讨论组。判断自己发的消息只有群消息才有效

**Comment by pandolia** [comment]
不好意思，我的错。。。文档里面写错了，那段代码只对群消息才有效。

**Comment by Nugine** [comment]
emmmm，其实之前在群里也发现了相同的问题。。。
示例代码未能识别自身发出的消息。
我中午再测试一下。

**Comment by pandolia** [comment]
我知道问题了，你的版本是2.2.14，需要升级到2.3.5版。“检测自己发消息” 的功能是 2.3 版中才增加的。群消息和讨论组消息都可以检测出来。

**Comment by pandolia** [comment]
2.2 版和 2.3 版可能有细微的差别，请看 https://github.com/pandolia/qqbot/issues/171

**Comment by Nugine** [comment]
明白了，感谢解答！
已更新到v2.3.5，我用member.qq==bot.conf.qq来判断。
不过为什么仅当接收到自己发出的消息时，member.uin与member.qq相同，而接收到其他人发出的消息时，member.uin和member.qq不相同？
![6](https://user-images.githubusercontent.com/30099658/29993180-ca9e1c02-8fe1-11e7-8e3e-7ad56de5783f.png)

**Comment by pandolia** [comment]
只有自己的是相同的，其他人都不相同。

**Comment by pandolia** [comment]
腾讯那边的设定就是这样的。

**Comment by Nugine** [comment]
OK，感谢解答！
