### ISSUE TITLE
漏掉消息

### ISSUE THREAD

**Issue by OUCWIND** [pandolia/qqbot#206]
有的长消息会收到的消息显示为空，这是怎么回事，是不是没收到

**Comment by pandolia** [comment]
https://github.com/pandolia/qqbot/issues/200

**Comment by OUCWIND** [comment]
有你说的那种长消息变成几条短的消息，不过也有就是空的消息的

**Comment by pandolia** [comment]
哦，那估计还是webqq本身的问题啊。
