### ISSUE TITLE
运行一段时间后掉线检测不到

### ISSUE THREAD

**Issue by bigcat26** [pandolia/qqbot#21]
运行一段时间之后，没有打印任何任何日志，其他qq看到这个qqbot是离线的
但是qqbot检测不到自己已经离线了。qqbot是否有定时检测自己是否正常在线？
鹅厂会强制webqq定时踢下线吗？

**Comment by pandolia** [comment]
你试试用其他qq向这个qq发信息能否收到？一般2天左右才会被踢下线。

**Comment by bigcat26** [comment]
收不到的消息的，重新运行是要重新扫码才能登录（我用了会话保存）。
然后也遇到过一次公网断开程序抛异常。

**Comment by pandolia** [comment]
重新登录一次后面应该好了。
