### ISSUE TITLE
termServer的默认IP问题

### ISSUE THREAD

**Issue by lvsenlin** [pandolia/qqbot#210]
termServer的ip默认是127.0.0.1，能改成命令行、配置文件可定义吗？
因为在docker中用到，跨docker访问会很麻烦~要下源码，改源码……

**Comment by pandolia** [comment]
为了安全起见，暂时不考虑提供用配置文件修改此 ip 的功能。可以考虑使用端口映射。
如果确实需要修改，可以在 onInit 回调里面修改这个 ip ，这样就不需要改源码了，示例代码：

    def onInit(bot):
        import qqbot.qterm; qqbot.qterm.HOST = '123.123.123.123'

将以上文件保存为 changip.py ，放到插件目录。再在控制台输入： qqbot -pl changip 。则 qqbot 会在启动时修改 ip 。

**Comment by lvsenlin** [comment]
非常感谢~
