### ISSUE TITLE
如何自定义日志格式？

### ISSUE THREAD

**Issue by lawulu** [pandolia/qqbot#211]
我自定义一个plugin，使用logging记录下某个群所有的接受到的消息，但是系统默认的日志输出也输出到该文件了。
类似这种：
[2017-09-19 23:57:13]  来自 群“python技术交流群”[成员“lwl”] 的消息:"“越过长城，走向世界”"

看了下源代码，

            INFO('来自 %s 的系统消息： "%s"', contact, content)
也输出到我自定义的日志文件了，如何能把两种分开？

**Comment by pandolia** [comment]
可能你用的是 root logger 。你需要定义一个其他名字的logger。比如：

    logger = logging.getLogger("mylogger")
    logger.addHandler(...)
    logger.info('xxx')

**Comment by lawulu** [comment]
Thanks 明白了。
