### ISSUE TITLE
请问能在py文件中import qqbot吗?

### ISSUE THREAD

**Issue by liujiachao** [pandolia/qqbot#213]
我想在一个py文件中使用qqbot，在这个py文件中利用qqbot发消息等功能，而不是使用命令行，请问这样可以吗？ 我应该怎么使用呢？ 谢谢。

**Comment by pandolia** [comment]
先在独立的进程中运行qqbot。
再在你的py文件中调用qqbot的http接口。比如: http://127.0.0.1:8188/send/buddy/qq=123456/nihao
