### ISSUE TITLE
近期(0929)不能及时收到讯息

### ISSUE THREAD

**Issue by Tiande** [pandolia/qqbot#215]
版本 V2.3.5
尝试了在 **家(Win10+河南电信)** 与 **腾讯云服务器(Win2008R2+上海线路)**。

1. 均不能即时获取数据(间隔几分钟才会刷新一次)。
2. 有时命令行会假死(需要手动回车才能更新)。

之前一直是好好的，不知道是否只有我出现了这个问题？

**Comment by Tiande** [comment]
换了个大号QQ，没有这些问题了。
大概是被限制了获取频率？
没有被封号真是万幸。
可是没有那么多高等级QQ也很为难...

**Comment by Nugine** [comment]
遇到了同样的问题。。。
重新启动能获取一两次数据，然后暂时没有响应

**Comment by ctlPython** [comment]
接收不到数据
