### ISSUE TITLE
挺好的一个bot

### ISSUE THREAD

**Issue by pokemonchw** [pandolia/qqbot#217]
说说经验……
虽然文档里强调说，绝对不要用os.system
但是只是system
如果要从定时任务里执行的话，可以考虑os.popen

**Comment by pandolia** [comment]
谢谢！
文档的意思是说不要在 onQQMessage 函数内用os.system 执行 qq send 之类的命令，比如： os.system('qq send buddy xxx hello')  ，这样调用会造成死锁。这时候应该使用 bot.SendTo 方法。
用 os.system 执行其他的系统命令是没问题的。
