### ISSUE TITLE
SMTPAuthenticationError: (535, 'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

### ISSUE THREAD

**Issue by yuanhr** [pandolia/qqbot#221]
SMTPAuthenticationError: (535, 'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

时好时坏，有的时候能够通过扫码登录进去，但是有的时候，就报上述错误，请问是什么原因？

**Comment by pandolia** [comment]
出现这个错误的原因是因为未提供正确的邮箱 IMAP/SMTP 服务授权码。

**Comment by pandolia** [comment]
这个错误信息的链接里面有设置授权码的方法。
http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256

**Comment by yuanhr** [comment]
一直用的是同一个授权码，但是有的时候登得上，有的时候就报上述错误，很奇怪

**Comment by yuanhr** [comment]
[2017-10-11 20:03:00] [ERROR] 无法和腾讯服务器建立私密连接， 5 秒后将尝试使用非私密连接和腾讯服务器通讯❯
477231 [2017-10-11 20:03:05] [WARNING] 开始尝试使用非私密连接和腾讯服务器通讯。

请问为什么会出现这种情况，有时候连接会等待很久，非常影响效率。

**Comment by pandolia** [comment]
重新申请一下授权码吧，注意要申请imap/smtp协议的授权码。
私密连接应该只需要等5秒吧，而且就第一次需要等。

**Comment by jenniferchiang** [comment]
> 这个错误信息的链接里面有设置授权码的方法。
> http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
感谢！！！
