### ISSUE TITLE
请问表单提交之后，PHP使用exec()输出，内容填中文在QQ上就乱码。英文就不会，要怎么解决呢？

### ISSUE THREAD

**Issue by huaiyin0416** [pandolia/qqbot#226]
![1](https://user-images.githubusercontent.com/32978395/31850481-edb68610-b684-11e7-9008-2e9c8b200af5.png)
![2](https://user-images.githubusercontent.com/32978395/31850482-eeb049b6-b684-11e7-9baf-20501f1083dc.png)

**Comment by pandolia** [comment]
php 的 exec 函数执行含中文命令的问题，可以参考下这篇文章： https://mikecoder.cn/?post=135
