### ISSUE TITLE
请问，有什么办法实现对群里其他qq发消息？

### ISSUE THREAD

**Issue by shaoshoutianheyu** [pandolia/qqbot#227]
希望实现题目所说功能，获取能够获取群内所有QQ用户的qq账户？
请问，qqbot可以实现吗？怎样实现呢？

**Comment by pandolia** [comment]
可以获得群内所有成员的 qq 等资料，但不能发给这些成员发信息。
获取群成员的资料用 bot.List 接口就可以，详见文档的第五节。

**Comment by shaoshoutianheyu** [comment]
谢谢，再多问一句，你知道获取的qq资料有哪些吗？是否包括qq号。
还有，您指导雪球给他人发消息的开源项目吗？
万分感谢！

**Comment by pandolia** [comment]
可以获取到的资料详见这里： https://github.com/pandolia/qqbot/blob/master/qcontact-attr.md 。包括成员的 QQ 号也可以获取。

**Comment by pandolia** [comment]
bot.List 接口可以返回一个包含 “联系人对象（Buddy对象、Group对象等）” 的数组，你可以查看这些对象里有一些什么属性，就知道可以获取到哪些资料了。

**Comment by shaoshoutianheyu** [comment]
嗯。我已经获取到qq群qq号了，谢谢您到答复。另外，我想了解有哪些尝试可以给qq群到用户（非好友）发消息。我在尝试win32api、pywinauto，但还是没有打通这条路？盼大侠指点一下，谢谢！
