### ISSUE TITLE
对于重启的机制无法理解

### ISSUE THREAD

**Issue by xieldy** [pandolia/qqbot#228]
假设我现在有一个qqbot正在运行，那么它接收到‘--stop’消息之后，执行bot.stop()，那么他是否会第二天早上八点重新运行？若我在他重新运行之前又开了一个相同qq的qqbot，那么第二天早上八点两个进程会不会相互挤着登录？我这么说的理由是今早我发现我邮箱塞满了未读的二维码邮件。

**Comment by pandolia** [comment]
stop 之后整个进程就退出了，不会再重新运行了，你可以用 ps 命令查看验证一下。
你说的情况可能是其他原因引起的两个进程同时运行。
