### ISSUE TITLE
我想从另一个单独的程序发送指令给我的机器人

### ISSUE THREAD

**Issue by YBA0312** [pandolia/qqbot#235]
但是提示：
ttributeError: 'QQBot' object has no attribute 'SendTo'
头文件是哪个
我该怎么做？

**Comment by Lyttoni** [comment]
唔,你可以试着这样做(好好看文档...):
`from qqbot import _bot as bot
def send(msg):
    try:
        # Login QQ
        bot.Login(['-q', '2***5323', '-ip', '10.11.12.19'])
        # 通知qq群
        g = bot.List('group', 'abc')[0]
        bot.SendTo(g,msg)
    except Exception as msg:
send("hello")
`

但是我很郁闷,如何在Django中调用qqbot ?

**Comment by Lyttoni** [comment]
昨晚又仔细看了下文档, 我想你可以这么做：
在命令使用qqbot启动和登陆后，qqbot会提供一个Web接口：127.0.0.1:8188

**Comment by YBA0312** [comment]
感谢大大！
