### ISSUE TITLE
关于二维码服务器的问题~大佬快到碗里来

### ISSUE THREAD

**Issue by SuperSuperSuperSuper5** [pandolia/qqbot#238]
问题大概是这样的，qq不是差不多两天就会要求重新登录嘛，然后我看文档里面可以设置一个二维码服务器
![这里](https://user-images.githubusercontent.com/13602602/33000801-1e44ea66-cde5-11e7-977e-102cb33c28a0.png)

然后我就按着文档设置了一下，发现不能用，端口已经开了

![我的设置](https://user-images.githubusercontent.com/13602602/33000821-47100b1a-cde5-11e7-890c-140e339e5c98.png)

`firewall-cmd --list-port` 显示`9999`端口已经打开了

但是我访问这个地址发现无法访问

![结果如下](https://user-images.githubusercontent.com/13602602/33000903-acc475e0-cde5-11e7-8382-76fcc01b037b.png)

不知道是哪里配置失误了还是什么滴，请大神们明示~~☆⌒(*＾-゜)v THX!!

---

然后我刚刚细细看了一下输出，发现这里显示这个

![error](https://user-images.githubusercontent.com/13602602/33001032-772a3c84-cde6-11e7-8ad8-3f2277350a7b.png)

这个又是神马原因😂

**Comment by pandolia** [comment]
我也没碰到过。还是不要用这个服务器吧。可以用邮箱模式替代？

**Comment by SuperSuperSuperSuper5** [comment]
好滴,哪天我看看代码修改一下看看哈哈哈

**Comment by pandolia** [comment]
还可以看看新发布的passwordlogin插件，直接使用用户名密码登录，不需要扫码了。
