### ISSUE TITLE
关于全局变量

### ISSUE THREAD

**Issue by Stanla** [pandolia/qqbot#245]
插件编写中会用到全局变量，但似乎用不了，求教如何在插件中使用全局变量

**Comment by pandolia** [comment]
可以用的吧。回调函数里面可以访问全局变量的啊。

**Comment by pandolia** [comment]
x = 1

**Comment by Stanla** [comment]
我是直接在onmessage里调用subprocess模块，
这样：
def execcmd(cmd):
    r=subprocess.Popen("xxxx")
    return r
execcmd(cmd)
r.poll()
......
然后报错说r是未定义的全局变量

**Comment by pandolia** [comment]
这种情况下需要在你的 execcmd 函数的开头加一句 global r 。

**Comment by pandolia** [comment]
你可以先学习一下 python 中全局变量的使用方法。
