### ISSUE TITLE
怎样不回复自己的消息？我设置了却没起效果

### ISSUE THREAD

**Issue by jxg972** [pandolia/qqbot#246]
`# -*- coding: utf-8 -*-
import sys,requests,time

def onQQMessage(bot, contact, member, content):
	if contact.qq!="XXX":`
我通过contact.qq!="XXX"的方式，避免回复自己的消息变成死循环，但是程序依然会不停的回复自己，怎么解决？

**Comment by pandolia** [comment]
有个 bot.isMe 方法。

**Comment by pandolia** [comment]
示例代码：

    def onQQMessage(bot, contact, member, content):
        if bot.isMe(contact, member):
             print('This is me')

**Comment by jxg972** [comment]
收到，谢谢，我用的是笨方法
