### ISSUE TITLE
关于邮箱接收二维码的问题

### ISSUE THREAD

**Issue by ruQian** [pandolia/qqbot#248]
受到的二维码过期并将邮件标记为已读，后续再也收不到邮件了。是不是该功能还没有实现?

**Comment by ruQian** [comment]
@pandolia

**Comment by pandolia** [comment]
这个功能已实现。

**Comment by pandolia** [comment]
当邮箱模式和服务器模式同时开启时，发邮件时不会发送真正的图片，只会将图片地址发到邮箱中去，而且只发送一次，二维码过期时刷新一下邮件就可以了。

如果只开启邮箱模式，则发邮件时会发送真正的图片，当二维码过期时，需要将邮件设置为已读（用手机 QQ 点开邮件后该邮件就是已读了），之后才会发送最新的二维码图片。

**Comment by pandolia** [comment]
你可能是同时开启了服务器模式，所以只发送一次。
