### ISSUE TITLE
消息重复发送的问题什么时候解决啊？

### ISSUE THREAD

**Issue by yuansuye** [pandolia/qqbot#251]
一般情况都没这问题，但是在一个大型群发消息时，常常会出现重复发送的问题，加了time.sleep也没用。。。

**Comment by pandolia** [comment]
试试把 bot.SendTo 的第三个参数设置为 False 。

**Comment by pandolia** [comment]
bot.Sendto(contact, "hello", False)

**Comment by yuansuye** [comment]
@pandolia 我试试。
