### ISSUE TITLE
请问端口的关闭可以通过寻找其他接口修复么？如果可能需要多久？

### ISSUE THREAD

**Issue by jinyuqilin1** [pandolia/qqbot#259]
如果需要的话我们都可以帮忙。。。

**Comment by lvsenlin** [comment]
日志中提示：请求“http://qun.qq.com/cgi-bin/qun_mgr/get_group_list”时出现 请求被拒绝错误, html='{"ec":1,"em":"no&nbsp;login"}'
发消息时提示：QQBot 在向 QQ 服务器请求数据获取联系人资料的过程中发生错误

盼大神修复~

**Comment by pandolia** [comment]
目前来看，qun.qq.com这边的接口都不能用了。没找到可替换的接口。。。

**Comment by lvsenlin** [comment]
http://s.web2.qq.com/api/get_user_friends2这个接口中，有可以用的吗？
在result.info中
![image](https://user-images.githubusercontent.com/3062415/34553348-f6735dc4-f161-11e7-9501-5457616308ab.png)
![image](https://user-images.githubusercontent.com/3062415/34553358-06078080-f162-11e7-9e84-4e61896685bb.png)

**Comment by lvsenlin** [comment]
了解了，那把备注全改成QQ号，是不是就好实现很多了

**Comment by 1098880928aa** [comment]
QQ好友的话应该可以通过改备注为qq号来区分好友，但是QQ群好像就没办法用这个方法啦
