### ISSUE TITLE
为什么去掉服务器模式二维码登录?

### ISSUE THREAD

**Issue by bigcat26** [pandolia/qqbot#26]
我觉得这个功能还挺好的?

**Comment by spdv123** [comment]
Unix的机子一般都是用nohup跑的吧，服务器如果是windows也可以开二维码登陆啊

**Comment by pandolia** [comment]
我觉得现在邮箱模式已经够用了，而且掉线后能自动重发到邮箱随时随地扫码，非常方便啊。服务器模式如果大家认为需要的话，下一版中再加回来吧。

**Comment by pandolia** [comment]
主要是之前共三种模式来显示二维码，选项太多了，怕用户烦。

**Comment by ByCnck** [comment]
还是希望能加回来，邮箱虽然能收到二维码但有时候不方便扫描（时间长了，二维码会过期）。web的话想什么时候扫都可以

**Comment by pandolia** [comment]
最新版的2.0.2版已经重新增加了服务器模式，欢迎大家试用。^_^
