### ISSUE TITLE
已发布 v2.3.8 ，删除 qun.qq.com 相关代码

### ISSUE THREAD

**Issue by pandolia** [pandolia/qqbot#261]
所有联系人（好友/群/群成员/讨论组/讨论组成员）的真实 QQ 都没办法获取了。

**Comment by lvsenlin** [comment]
辛苦了，用备注发消息可以实现吗？

**Comment by pandolia** [comment]
可以的。

**Comment by aes3219563** [comment]
大佬辛苦了，向你致敬

**Comment by lvsenlin** [comment]
我试了一下，好像只能用网名发。把备注改成QQ号，好像不行，qq send buddy 'QQ号' 'test'
是不是要改一下代码？

**Comment by pandolia** [comment]
qq send buddy mark=QQ号 test

**Comment by lvsenlin** [comment]
OK，666
