### ISSUE TITLE
获取 群 / 讨论组 达到上限

### ISSUE THREAD

**Issue by Kunsect** [pandolia/qqbot#266]
最多只能接受到 100 条的信息吗？

**Comment by pandolia** [comment]
没有这个限制啊。

**Comment by Kunsect** [comment]
我这边有 400 多个讨论组，但是用 API 遍历的时候只能拿到前 100 条数据，而且用 smart QQ 的 API 也是只能拿到 100 条，请问有什么好的解决办法吗？

**Comment by pandolia** [comment]
你用浏览器打开 w.qq.com 网页看看能不能拿到所有数据。如果网页上不能拿到，那应该是没办法了。

**Comment by Kunsect** [comment]
是的，就是通过网页获取的，发现也是只能拿到 100 条。。
