### ISSUE TITLE
偶发掉线不会自动重新登录

### ISSUE THREAD

**Issue by aRe00t** [pandolia/qqbot#274]
![image](https://user-images.githubusercontent.com/1515224/35076242-5a2444fc-fc32-11e7-8dc5-e8c8bfe57597.png)

你好, qqbot 有时会自动重启, 有时就直接退出了.
两次退出现象间隔约为1~3天不等.

版本: 2.3.9

使用方式
```
from qqbot import QQBotSlot as qqbotslot
from qqbot import _bot as bot

@qqbotslot
def onQQMessage(bot, contact, member, content):
    pass

bot.Login(['-u', 'user'])
bot.Run()
```

**Comment by pandolia** [comment]
建议改用插件模式，本文件修改为：

    def onQQMessage(bot, contact, member, content):
        pass

再启动 qqbot ，注意开启自动重启模式。

    qqbot -u user -r

最后加载本文件：

    qq plug sample

**Comment by aRe00t** [comment]
非常感谢, 我试试.
已升至 2.3.10

**Comment by aRe00t** [comment]
观察了快一天, 自动重启正常了, 多谢.
