### ISSUE TITLE
2.0 版和 1.x 版的差别

### ISSUE THREAD

**Issue by pandolia** [pandolia/qqbot#28]
本次 2.0.1 版对本项目进行了大的重构，相对于之前的 1.x 版功能进行加强，代码改动量非常大，很多接口都不再兼容了。主要的差别有：

（1） QQBot 类拆分
1.x 版中 QQBot 类太庞大了，登录数据和联系人数据和全搅在一起，管理非常不便。联系人的查询接口只有 getBuddyByUin 之类的，功能简单，且十分难记。

本次将原来的 QQBot 类的功能拆分为 QSession 类和 QContacts 类，前者管理登录数据，只负责和腾讯服务器通讯，后者管理联系人数据，只负责联系人的保存和查询。

新的 QQBot 类对 QSession 对象和 QContacts 对象进行统一管理，只提供 List/Get/SendTo/Send/On 五个接口，使用更方便，联系人查询功能更强大，可根据 QQ号、uin 和网名进行查询。

（2） 程序的运行方式
程序目前采用 消息/响应 的方式运行，后台开启三个子线程，分别运行 pollForever 、 fetchForever 和 termServer.Run ，分别负责 QQ消息轮询 、 联系人资料获取 和 qterm 客户端消息监听，子线程收到消息或完成联系人资料获取时，会向主线程发消息（实际是将一个 Message 对象放入一个消息队列中去）。主线程不停的从消息队列中取出消息，并根据消息类型调用相应的回调函数。所有对联系人资料的查询和更新等操作均在主线程中完成，避免了多个线程对同一个数据进行操作。

（3） 其他
qq 和 uin 均已字符串的形式保存（之前是 int ）。
少量通用函数的名称进行了改变。

如果使用过程中还有其他问题，请发邮件给我（pandolia@yeah.net）。

**Comment by shangguan1997** [comment]
加上了readline模块 所以现在windows已经被无情抛弃了吗 23333

**Comment by pandolia** [comment]
windows 也可以用的啊。我这边已经测试过了。windows下也可以 import readline 的啊。我装的是 python(x,y)， 很多库自动装好了。如果 windows 下不能用，可以改为：

    try:
        import readline
    except ImportError
        pass

不影响使用的。

**Comment by shangguan1997** [comment]
呃呃 我用pip装readline总是提示
error: this module is not meant to work on Windows
还有就是bot.SendTo(message.contact,u '你好，我是QQ机器人')
这样加上u会出现编码错误？？

**Comment by pandolia** [comment]
是的。程序中几乎所有字符串都是 str 对象（ utf8 编码），不是 unicode 。

**Comment by shangguan1997** [comment]
程序在接受多条信息之后就不再接收消息了
我一开始以为是我的问题，然后我用了你给的样例程序测试了一下
也是这样子,在控制台不输出INFO消息

**Comment by pandolia** [comment]
我这边运行还是好的。你打开 -d 选项再运行一下，看看输出的调试信息有什么。

**Comment by pandolia** [comment]
再试试能否用 qterm 发消息？

**Comment by pandolia** [comment]
重新手动登录一下应该可以解决这个问题。

**Comment by gesoarek** [comment]
没有继承QQBot然后重写方法的途径了么?
qterm能否不启动呀

还一个可能是urllib3的问题
/usr/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

我在Windows 没有遇到，Linux 遇到了这个问题，已经安装了certifi 依然一直刷waring。不知道有没有小伙伴遇到的

**Comment by pandolia** [comment]
现在用继承的方式稍微麻烦一点，可以用下面的方式。

    class MyQQBot(QQBot):
        def __init__(self, *args, **kwargs):
            QQBot.__init__(self, *args, **kwargs)
            self.On('qqmessage', MyQQBot.onQQMessage)
    
        def onQQMessage(self, msg):
            pass

也可以继承一个 BasicAI 类，具体你可以研究一下 QQBot 类的代码。

qterm 是强制启动的，如果不想要这个功能，需要修改 qqbot.py 文件，把 termServer 相关的代码注释掉就行。

那个 warning 跟 request 库和 certifi 库有关，windows 下，只有 requests==2.7.0 和 certifi==2015.4.28 版本下才可以正常使用。linux 下某些其他版本也能用。

以下代码可以 disable 这个 warning ：

    from requests.packages.urllib3.exceptions import InsecureRequestWarning
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
