### ISSUE TITLE
list命令的输出无法显示特殊字符

### ISSUE THREAD

**Issue by Moe-New** [pandolia/qqbot#282]
list命令的输出无法显示特殊字符,如表情符号,日语等,但在qqbot的运行输出里面是正常的,这个有办法解决吗?

**Comment by pandolia** [comment]
list 命令为了表格输出对齐，对特殊字符做了过滤处理。你可以使用 http://127.0.0.1:8188/list/buddy 接口。

**Comment by 716438031** [comment]
感谢~话说,有打算做个插件调用图灵机器人吗?
