### ISSUE TITLE
从本地缓存加载pickle时用户名不会更新

### ISSUE THREAD

**Issue by Naville** [pandolia/qqbot#3]
必须删除pickle重新登录后self.nick才会刷新

**Comment by pandolia** [comment]
是的。为了加快自动登录的速度，自动登录只是简单的 load 一下上次登录保存的 pickle ，不会向腾讯服务器请求新的用户信息。如果需要刷新 self.nick ，可以使用手动登录。

**Comment by pandolia** [comment]
不需要删除 pickle ，只需要用不带参数的方式运行一下本程序就可以了。

**Comment by Naville** [comment]
是的但这不是需要重新auth？
贼麻烦啊

**Comment by pandolia** [comment]
嗯，是有点麻烦。您可以在 autoLogin 方法的最后加上：

    self.fetchBuddy()
    self.nick = dict(self.buddy).get(self.qqNum, self.nick)

这样自动登录成功后也会更新好友列表和自己的昵称了。

**Comment by pandolia** [comment]
不需要重新 auth 了。

**Comment by pandolia** [comment]
经过测试，可以在 autoLogin 方法的最后加上：

        self.nick = self.smartRequest(
            url = ('http://s.web2.qq.com/api/get_friend_info2?tuin={uin}&vfwebqq={vfwebqq}&' + \
                   'clientid=53999199&psessionid={psessionid}&t=0.1').format(**self.__dict__),
            Referer = 'http://s.web2.qq.com/proxy.html?v=20130916001&callback=1&id=1'
        )['nick'].encode('utf8')

这样可以更新自己的昵称。

**Comment by Naville** [comment]
orz非常感谢，这点为什么不作为一个可选选项并入master呢

**Comment by pandolia** [comment]
@Naville 感谢您的帮助和支持，我已经增加了一个 refetch 命令，这样登录后如果有需要可以重新获取一下好友列表等，同时会更新自己的昵称。

**Comment by tetsaicn** [comment]
求助啊，refresh怎么调用

**Comment by pandolia** [comment]
2.0版中已经去掉了 refetch 命令，改为在后台每隔 5 分钟自动 fetch 一次所有联系人列表。
