### ISSUE TITLE
群管理命令接口无法正常使用

### ISSUE THREAD

**Issue by reInkn** [pandolia/qqbot#312]
设置/取消管理员： bot.GroupSetAdmin(group, membs, admin=True)
设置/取消群成员名片： bot.GroupSetCard(group, membs, card)
禁止群成员发言： bot.GroupShut(group, membs, t=60)
踢除群成员： bot.GroupKick(group, membs)
以上四条均有尝试，但全无结果，也没有反馈就直接结束程序
请问是出现了什么问题？

**Comment by pandolia** [comment]
群管理的接口已失效，抱歉。
