### ISSUE TITLE
linux服务器上无图形界面，passwordlogin插件无法使用

### ISSUE THREAD

**Issue by dengwenwen** [pandolia/qqbot#317]
linux服务器上无图形界面，最新版selenium又不支持phantomjs，passwordlogin插件无法使用。能改成无图形界面操作系统上支持使用chrome或firefox的headless么？

**Comment by dengwenwen** [comment]
耶~，我改好了

**Comment by yylzcom** [comment]
@dengwenwen 请问能说一下具体怎么修改的吗

**Comment by QingGo** [comment]
qqbot本身的设置文件并不支持chrome和Firefox的headless模式，需要自行修改passwordlogin.py插件。
