### ISSUE TITLE
pip install -r ?

### ISSUE THREAD

**Issue by fritx** [pandolia/qqbot#323]
readme里的cd进入目录 的安装指令
应该是 `pip install -r requirements.txt`？

我直接 `pip install` 会提示

```plain
qqbot$ pip install
You must give at least one requirement to install (see "pip help install")
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by pandolia** [comment]
`pip install .`

**Comment by pandolia** [comment]
最后有个 “”.“”

**Comment by fritx** [comment]
![image](https://user-images.githubusercontent.com/6647633/39992398-36fa9638-57a5-11e8-873b-f72209676189.png)

哦哦~~ readme上没展示好 不熟悉python 哈哈
