### ISSUE TITLE
每隔一段时间就会出现二维码且一更改v2.3.conf就报错（win10）

### ISSUE THREAD

**Issue by I-love-study** [pandolia/qqbot#327]
在python调用QQbot后，我一旦打开他就会每个一段时间就出现二维码（即使我已经扫描过）
并且我一旦更改v2.3.conf文件后，他就会显示：
配置文件 C:\Users\ASUS_A84S\.qqbot-tmp\v2.3.conf 错误: invalid character in identifier (<unknown>, line 1)
甚至于我只要用笔记本打开，什么都不动得保存后，就会有这行字（是UTF-8）

**Comment by pandolia** [comment]
试下用 sublime 或 pycharm 编辑配置文件。
