### ISSUE TITLE
适用于智能客服的场景吗

### ISSUE THREAD

**Issue by LinoMay** [pandolia/qqbot#328]
如题，主要是想qq自动回答一些常见问题咨询

**Comment by tiamit** [comment]
常见问题还行，但是批量化生产肯定受不了的。
在2018年05月31 05时49分, "LinoMay"<notifications@github.com>写道:

如题，主要是想qq自动回答一些常见问题咨询

**Comment by LinoMay** [comment]
谢谢解答。我们主要是一个业务系统，运维人员需要反复回答常见的、重复的问题，为解决这样的情况，若是该项目无法满足，有推荐的解决方案吗？或者思路也行

**Comment by tiamit** [comment]
按照腾讯公司多年来经营的例子我总结出，他要么让你买营销QQ，要么让你付钱。
在2018年06月01 07时18分, "LinoMay"<notifications@github.com>写道:

谢谢解答。我们主要是一个业务系统，运维人员需要反复回答常见的、重复的问题，为解决这样的情况，若是该项目无法满足，有推荐的解决方案吗？或者思路也行

**Comment by LinoMay** [comment]
好吧。不管怎么样还是谢谢你。
