### ISSUE TITLE
 from qqbot import _bot as bot

### ISSUE THREAD

**Issue by ID-TIAN** [pandolia/qqbot#329]
新建的py文件，命令窗口打开报错，为什么
 from qqbot import _bot as bot
ImportError: cannot import name '_bot'
如果命令行python中输入 from qqbot import _bot as bot，就不会报错，怎么解决

**Comment by ID-TIAN** [comment]
@pandolia

**Comment by pandolia** [comment]
你可能是把自己的脚本命名为 qqbot.py 了。

**Comment by ID-TIAN** [comment]
@pandolia  我没有写过这样名字的脚本

**Comment by pandolia** [comment]
有没有将文件夹命名为 qqbot ？

**Comment by pandolia** [comment]
你可以试下在你的py文件的最开头加入：

    import qqbot; print(qqbot.__file__)

看看打印出什么。

**Comment by ID-TIAN** [comment]
@pandolia 
F:\python_lian xi\qq\qqbot.py
F:\python_lian xi\qq\qqbot.py
打印这个

**Comment by pandolia** [comment]
把这两个文件删除就可以了。

**Comment by ID-TIAN** [comment]
非常感谢！

**Comment by ID-TIAN** [comment]
def  onQQMessage(bot,contact,member,content):
这个函数能不能定义到
from qqbot import _bot as bot
bot.Login()
的后面
@pandolia

**Comment by pandolia** [comment]
你还是用插件模式来开发吧，不要自己去调用 bot.Login 。

**Comment by pandolia** [comment]
只需要写好 onQQMessage 函数，再加载插件就 ok 了。

**Comment by ID-TIAN** [comment]
我想要把他打包在一起，然后换成exe，在其他电脑上运行。
如果用插件，怎么打包
@pandolia

**Comment by pandolia** [comment]
哦，用插件不太好打包，你可以这样写：

    from qqbot import qqbotslot, Runbot

    @qqbotslot
    def onQQMessage(...)
         ...

    Runbot()
