### ISSUE TITLE
创建此终端的子进程时出错

### ISSUE THREAD

**Issue by breezefaith** [pandolia/qqbot#33]
执行子进程“python /usr/local/lib/python2.7/dist-packages/qqbot/qterm.pyc 8188”失败(没有那个文件或目录)

**Comment by pandolia** [comment]
这个错误出现在 qterm.py 第 30 行的 CallInNewConsole(['python', __file__, str(self.port)]) ，不清楚为什么在你的系统中会找不到 /usr/local/lib/python2.7/dist-packages/qqbot/qterm.pyc 这个文件。你试试把 qterm.py 文件中那行改为 CallInNewConsole(['qterm', str(self.port)])， 看看有没有用。

**Comment by hucuyuu** [comment]
我也遇到了这种情况，但改过后依然执行子进程失败，可能是ubuntu下文件夹权限问题，新打开一个终端再敲qterm就可以了

**Comment by breezefaith** [comment]
万分感谢

**Comment by FrostMiKu** [comment]
这个问题在Kali Linux下也存在，我是python QQBot.py 启动的程序，同理python qterm.py 8188就行了

**Comment by pandolia** [comment]
gnome-terminal 3.22.1 下的此问题已修正，详见 https://github.com/pandolia/qqbot/pull/53/commits/bebaaab466f209784ca9f6b661675caa0c6d31fd ，请各位再试一下还有没有问题。感谢 @hjiayz 提供代码。
