### ISSUE TITLE
每天8点左右就掉线，定时重启没作用，只能重启进程

### ISSUE THREAD

**Issue by coolads** [pandolia/qqbot#333]

**Comment by pandolia** [comment]
掉线的事情没办法解决。
可以使用 schedrestart 插件，每天重启并手工扫码登录一次，基本可以保持持续在线。缺点就是每天都要人工扫码一次。

**Comment by tiamit** [comment]
可惜。

使用AquaMail for Android发送
http://www.aqua-mail.com


在 2018年6月19日 上午11:41:53 pandolia <notifications@github.com> 写道:

**Comment by coolads** [comment]
好吧，而且据观察每2天都在8点左右cookie失效。

**Comment by liang55** [comment]
设置了8：00定时重启    下午四五点掉线，没有触发掉线发送邮件重新登录啊
