### ISSUE TITLE
公开接口，Login/Stop/Restart/FreshRestart，均会提示SystemExit:202/1/0

### ISSUE THREAD

**Issue by dawnset** [pandolia/qqbot#334]
An exception has occurred, use %tb to see the full traceback.
SystemExit:202/1/0
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

使用jupyter notebook调用，在ide中循环执行命令，上述指令都没作用

**Comment by pandolia** [comment]
在有些 IDE 中运行时重启、停止命令会出问题。在命令行中运行不会出问题。

**Comment by dawnset** [comment]
好的，我研究研究如何通过命令行运行脚本
