### ISSUE TITLE
能否做到启动时自动获取群列表？

### ISSUE THREAD

**Issue by BillHMax** [pandolia/qqbot#336]
每一次刚刚启动qqbot的时候都要先在群里说一句话才能触发qqbot获取群列表，能不能让qqbot获取完群列表后再启动

**Comment by pandolia** [comment]
有一个 startAfterFetch 选项，打开这个选项就可以了，如： qqbot --startAfterFetch 。

**Comment by pandolia** [comment]
不过获取群列表的服务今天挂了，暂时还用不了。

**Comment by BillHMax** [comment]
好的，谢谢
