### ISSUE TITLE
还没登录的qqbot进程

### ISSUE THREAD

**Issue by SuedeOO** [pandolia/qqbot#339]
你好，
登录成功的qqbot可以通过 qq {port} stop 也可以在终端control-c 终止它
请问一下通过subprocess.run('qqbot -p port', shell=True)， 但是没有登陆成功的qqbot进程该通过什么办法结束它呢？谢谢！

**Comment by pinohans** [comment]
```
p = subprocess.run('qqbot -p port', shell=True)
if p.poll() == None:
    p.kill()
```
如果确定子进程`p`没有成功登陆，首先需要用`poll()`判断进程状态（`None`表示正在运行），用`kill()`结束进程。

**Comment by SuedeOO** [comment]
我试过`p = subprocess.Popen('qqbot -p port', shell=True)`
然后用 `p.kill()` 或者 `os.kill(p.pid, signal.SIGINT)` 

还试过 `p = pexpect.spawn(‘qqbot -p port’)`
然后用 `p.sendcontrol('c')` 或者 `p.close`

这两种方法都没有用
在终端输入 `ps -ef|grep qqbot` 的时候进程还是在

**Comment by pandolia** [comment]
qqbot 内部会调用 Popen('qqbot ...') 生成一个 qqbot 子进程。用 p.kill 无法杀死这个子进程。

**Comment by pandolia** [comment]
登录不成功不会自动退出，需要手动杀。
