### ISSUE TITLE
一直提示 Unverified HTTPS

### ISSUE THREAD

**Issue by auroreme** [pandolia/qqbot#34]
中间两句一直提示

```
# [INFO] 来自 ...
# /usr/lib/python2.7/site-packages/requests-2.12.5-py2.7.egg/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
# InsecureRequestWarning)
# [INFO] 来自 ...
```

**Comment by auroreme** [comment]
https://github.com/auroreme/docker-qqbot/blob/master/Dockerfile

**Comment by pandolia** [comment]
这个 warning 跟 request 库和 certifi 库有关，windows 下，只有 requests==2.7.0 和 certifi==2015.4.28 版本下才可以正常使用。linux 下某些高一点的版本也能用，版本太低就可能出错。

以下代码可以 disable 这个 warning ：

    from requests.packages.urllib3.exceptions import InsecureRequestWarning
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

**Comment by auroreme** [comment]
但是在 Linux 下默认就是安装的最新版本。

**Comment by whwq2012** [comment]
用virtualenv吧，我在virtualenv里弄的，可以正常运行

**Comment by auroreme** [comment]
@whwq2012 好的谢谢，不过我把 base image 换成 debian wheezy 貌似问题有解决了。

**Comment by pandolia** [comment]
我用的debian jessie，也可以。
这个问题可能是 urllib.open 的问题，明明系统中的浏览器都可以正常访问那个 https 网址，但用 requests.session.get 访问同样的网址却出错。。。
好像也没有很好的解决办法。。。
