### ISSUE TITLE
请问如何注册新人入群/退群的响应函数

### ISSUE THREAD

**Issue by ChineseYjh** [pandolia/qqbot#342]
我在大佬的changes里看到v2.1新加了这个功能，但是在README里没找到相应的内容。能解释下怎么用嘛...谢谢～

**Comment by pandolia** [comment]
这个功能已经失效了。

**Comment by ChineseYjh** [comment]
这样哇...呃那么有接口获得一个群的群成员列表嘛能说说接口用法嘛～谢谢～
