### ISSUE TITLE
关于新对象找不到的问题

### ISSUE THREAD

**Issue by Barrierml** [pandolia/qqbot#343]
您好，我在onQQMessage函数里面添加了一个新对象，再调试函数时，就会找不到那个对象，应该如何解决。

> 比如：

```
def onQQMessage(bot, contact, member, content):
    new = newclass（）
    new.fuc（）
```
当我再次调用onQQMessage时，它就会报错，找不到new，我在想是不是应该写到主函数里面，跟着主函数一起运行，但又无从下手，实在难堪，故来求教

**Comment by Barrierml** [comment]
暂时找到解决方案了，先把类的信息写到文件里面，每次函数都重新调用一遍。
不过这样副作用好大，每次回信息都多了2秒左右

**Comment by Barrierml** [comment]
是我没有引入import？请问都需要引入些什么模块

**Comment by pandolia** [comment]
需要引入 newclass 所在的模块啊。

**Comment by Barrierml** [comment]
当然引入了，不然的话，它应该第一次调用的时候就直接报错了。
它的报错信息是，找不到new，可能是onQQMessage每次执行完代码后就直接将内存释放了。
所以就试着每一次执行onQQMessage就重新载入一遍new，就不再报错了。
因为调用的是selenium + chrome对象，超级耗时间，要是每一次都重新加载的话，效率太低。
所以才想问一下，怎么样才能保证new不被释放，谢谢

**Comment by pandolia** [comment]
你可以把 new 当成一个全局变量，这样就只会调用一次 newclass() 了。

    new = newclass()
    def onQQMessage(bot, contact, member, content):
        new.func()
