### ISSUE TITLE
content可以获取原来格式的数据吗？

### ISSUE THREAD

**Issue by YanCunJu** [pandolia/qqbot#346]
现在获取的content并不是原本格式的数据，比如：
```
aaa
bbb
```
实际接受到的是`aaabbb`，换行符没有了？请问可以获取到原来有换行格式的数据吗？

**Comment by pandolia** [comment]
content是webqq接口返回的数据，可能是去掉了换行符的内容。
我测试了一下，如果是手机QQ发过来的消息，换行符不会被过滤掉。但若是PC-QQ发过来的消息，换行符都被过滤掉了。
