### ISSUE TITLE
README中的一个小错误

### ISSUE THREAD

**Issue by lenghonglin** [pandolia/qqbot#347]
在【四、实现你自己的 QQ 机器人】这个章节中的这句话【保持前面的 qqbot 进程运行，在另一个控制台输入 qq plug sample】，应该是运行“qq plug qqbot.plugins.sample”这条命令

**Comment by pandolia** [comment]
qq plug sample 也可以，只要你把 sample.py 放到可以被 import 的目录下就可以。
