### ISSUE TITLE
为什么不能群管

### ISSUE THREAD

**Issue by tetsaicn** [pandolia/qqbot#35]
禁言啊之类的，隔壁 perl的qqbot都可以了

**Comment by tetsaicn** [comment]
还有refresh怎么调用=-=

**Comment by tetsaicn** [comment]
既然都开issues了，我把这个问题一并提出来：自己发送的消息怎么看不到啊

**Comment by pandolia** [comment]
自己看不到是指对方收不到还是log里面没有？

**Comment by pandolia** [comment]
refresh 一般不需要自己调用，后台每隔五分钟会刷新一次联系人列表

**Comment by pandolia** [comment]
群管的功能后续版本再添加吧

**Comment by pandolia** [comment]
现在每发送一条消息，会打印一条 '向 xxx 发消息成功' 的信息。如果需要显示信息内容，可以将 qqbot.py 文件的第 75 行改为：
result = '向 %s 发消息成功，消息内容： %s' % (str(contact), message.content)

**Comment by pandolia** [comment]
如果是自己通过其他客户端（手机QQ，PC版QQ）发送的消息，那确实显示不出来，这是 WEB QQ 的限制。
其实你用手机QQ发消息，PC版QQ也显示不出来。
唯一能将所有客户端发送的消息显示出来的只有手机QQ。

**Comment by tetsaicn** [comment]
好吧，不能做消息收集了QAQ，自己的看不到无卵用啊，手机发送的消息电脑看得到啊
