### ISSUE TITLE
qq send 命令

### ISSUE THREAD

**Issue by BEE-JN** [pandolia/qqbot#351]
请问如果群名称有空格咋办
qq send group命令中以空格为断点

**Comment by pandolia** [comment]
可以通过修改源码绕过此问题。找到 termbot.py ，把第 127 行改为：

    cl = bot.List(args[0], args[1].replace('===', ' '))

发消息之前，把名字里面的空格替换为“===”，比如： qq send group 相遇江南===2018 a
