### ISSUE TITLE
'str' object has no attribute 'startsWith'

### ISSUE THREAD

**Issue by sakurayang** [pandolia/qqbot#352]
![bash_2018-07-25_12-54-54](https://user-images.githubusercontent.com/11017232/43180334-1e8ac0bc-900a-11e8-82c4-75c8007d4f30.png)
如图所示
代码：
```python
def onQQMessage(bot, contact, menber, content):
        if content.startsWith('-all'):
                arg = content[4:]
                bot.SendTo(contact , arg)
```
然后plug时显示plug成功，没过几秒钟就报错了，报错如图所示

**Comment by pandolia** [comment]
应该改为 startswith 。
