### ISSUE TITLE
无法将二维码发送至邮箱

### ISSUE THREAD

**Issue by MarStarck** [pandolia/qqbot#36]
(535, 'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

**Comment by pandolia** [comment]
这个字符串用 gbk 解码后是：
(535, 'Error: 请使用授权码登录。详情请看: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
应该是授权码不对，可能你用的qq邮箱的登录密码。
授权码需要在邮箱设置的页面上，申请开通 imap/stmp 服务后得到。
