### ISSUE TITLE
debian 8 默认配置不生效

### ISSUE THREAD

**Issue by BEWINDOWEB** [pandolia/qqbot#367]
### 背景及问题描述
在debian 8（64位） 百度云服务器上，系统已经配置好中文utf8了，用户配置生效，其他一切正常，唯一不正常的是默认配置不生效。我修改了默认配置后没有生效，虽然能够设置用户新的重启时间，但默认配置不更改导致8:00重启时间仍然存在。
结果就是，8:00重启一次（不想要的），23:00重启一次。
### 可能的问题原因
怀疑是名称是中文"默认配置"造成的，使用default可以避免这类隐患，但是现在无法改变任何的东西。
### 临时解决方法
1、找到这个文件：
find -name "\*schedrestart\*"
2、删除缓存并移动了这个文件：
```
rm ./usr/local/lib/python3.4/dist-packages/qqbot/plugins/__pycache__/schedrestart.cpython-34.pyc
mv ./usr/local/lib/python3.4/dist-packages/qqbot/plugins/schedrestart.py /root/.qqbot-tmp/plugins/
```
3、修改了用户配置：
```
        # 启动时需加载的插件
        "plugins" : [
            'schedrestart'
        ],

        # 插件的配置（由用户自定义）
        "pluginsConf" : {
            'schedrestart': '23:00',
        },
```

**Comment by BEWINDOWEB** [comment]
改了之后还是重启……而且提示信息不一样：
[2018-10-08 23:00:00] [INFO] 5 秒后重新启动 QQBot （手工登陆）
[2018-10-09 08:00:10] [INFO] 15秒后重新启动 QQBot （自动登陆，qq=xxxxxxxx）

**Comment by pandolia** [comment]
发一下完整的配置文件内容吧。
另外，如果你是按 qqbot -u somebody 的方式运行，那个 somebody 的用户配置会覆盖默认配置。

**Comment by pandolia** [comment]
另外， schedrestart 只会触发“手工登录”。
这个 8 点的自动登录，不是 sechedrestart 触发的，而是 cookie 过期，程序自动去尝试自动登录的。你看下这个 8 点“自动登录”的前面，有没有登录信息过期的log。

**Comment by pandolia** [comment]
8 点“自动登录”应该是被踢下线之后自动触发的。

**Comment by BEWINDOWEB** [comment]
> 无法长时间保持在线状态，每次登录成功后的 cookie 会每在 1 ~ 2 天后失效，将被腾讯服务器强制下线，此时 必须 重新登录。可以打开邮箱模式和自动重启模式，并配合 qqbot.plugins.schedrestart 插件使用，每天在固定的时间 手工扫码 登录一次，基本上可以稳定的保持在线状态。

我以为是每天扫码就不会被强制下线了……不应该呀，都重新获得新的COOKIE了，怎么时间还是一样地去计算呢，固定8点踢下去……

**Comment by pandolia** [comment]
没有解决办法了，这个 cookie 的过期时间是服务端设置的。客户端改不了。

**Comment by BEWINDOWEB** [comment]
嗯嗯，谢谢作者讲解，我再测试几天看看怎么处理。

**Comment by BEWINDOWEB** [comment]
尝试了一下在23点重启的时候清除登录的文件：
```
def onPlug(bot):
    g.t = bot.conf.pluginsConf.get(__name__, '23:00')
    g.hour, g.minute = g.t.split(':')

    @qqbotsched(hour=g.hour, minute=g.minute)
    def schedRestart(_bot):
        clearCookie()
        _bot.FreshRestart()

def clearCookie():
    os.system('cd ~/.qqbot-tmp/; rm *.db qq* *.pickle')

if __name__ == '__main__':
    clearCookie()
```
依然不行……

**Comment by TianYiFeiR** [comment]
为什么你们的聊天记录会在我邮箱里？
不知道这个邮件是不是应这样发。
