### ISSUE TITLE
输入双引号之后没有用

### ISSUE THREAD

**Issue by SesameWasher** [pandolia/qqbot#370]
输入指令后的结果（macOS Mojave）
gnd@snoW:~$ qq send group "MiraiAkari FansClub" 草
group-MiraiAkari 不存在
gnd@snoW:~$ qq send buddy "Kenny Fung" 草
buddy-Kenny 不存在

**Comment by pandolia** [comment]
解析指令的时候没有考虑双引号，有需要的话你可以修改下面这个文件的第25行：
https://github.com/pandolia/qqbot/blob/master/qqbot/termbot.py#L25

**Comment by SesameWasher** [comment]
请问具体该怎么做

**Comment by pandolia** [comment]
具体来说，当你执行 qq send group "Kenny Fung" xxx 时，下面这一行：
https://github.com/pandolia/qqbot/blob/master/qqbot/termbot.py#L25

    argv = command.strip().split(None, 3)

中的 command 就是 'send group "Kenny Fung" xxx' ，因此 argv 就是 ['send', 'group', '"Kenny', 'Fung" xxx' ] 。你所需要做的就是修改这一行，使得 argv = ['send', 'group', 'Kenny Fung', 'xxx'] ，才能达到你想要的效果。
