### ISSUE TITLE
群名字里面有特殊字符怎么办

### ISSUE THREAD

**Issue by hanwangkun** [pandolia/qqbot#373]
当向群发送消息时，如果群名字里面有特殊字符，比如群名：UI、UX 学习交流，
使用命令行发送命令会失败，提示群打不到，但是使用api发送则成功。

**Comment by pandolia** [comment]
有些特殊字符是不好处理，你可以在 termbot.py 的第 122 行下加一句 print(args) ，看一下用命令行发送和用 api 发送时的 args 有什么区别。
https://github.com/pandolia/qqbot/blob/master/qqbot/termbot.py#L122
