### ISSUE TITLE
邮箱配合 http 使用二维码有一些设定问题

### ISSUE THREAD

**Issue by Imr0219** [pandolia/qqbot#379]
1. 希望可以自定义发送的域名（不喜欢加端口访问，再云上增加一层反代后，邮箱推送的链接是错的）
2. 设置好 http 查看二维码后，希望邮件里再推送一份（邮箱只发送一个链接不是更麻烦了，虽然最初目的还是提示需要登陆）

还有个其他问题想请问下，README 中介绍发送命令，rinfo 具体指什么格式呢？

> 4） 消息发送命令
> 
>     qq send buddy|group|discuss $rinfo $message

**Comment by pandolia** [comment]
rinfo 就是接收者的信息，一般写他的昵称/备注名就ok了，需要严格控制可以填 nick=xxx, mark=xxx, uin=1234 等。

**Comment by pandolia** [comment]
第 1 、 2 个问题可以通过修改下面这个文件做到：
https://github.com/pandolia/qqbot/blob/master/qqbot/qrcodemanager.py

**Comment by Imr0219** [comment]
感谢解答，
根据您的回复和我的一些简单测试，rinfo 选项目前应该不支持查询（like）发送功能。用备注名是个不错的次选择，应该能满足
抱歉码代码能力不太行，我晚点试着改改看。
