### ISSUE TITLE
身份过期，号码存在风险问题

### ISSUE THREAD

**Issue by suxiaojack** [pandolia/qqbot#38]
长期登录时，如果超过了1、2天，总会出现身份过期错误的问题。而且再次登录时会被认为存在风险，需要手动重置密码恢复，这个怎么解决？这个是个很影响使用的问题！！

**Comment by pandolia** [comment]
换一个申请时间长一点的帐号，应该就没这个问题了。

**Comment by suxiaojack** [comment]
感谢答复！
