### ISSUE TITLE
登录信息过期，邮箱没收到新的二维码

### ISSUE THREAD

**Issue by liang55** [pandolia/qqbot#382]
运行一天后，发现掉线了 日志如下

[2018-11-28 17:29:40] [ERROR] 登录 cookie 很可能已过期
机器人异常结束 203 login-expire None
[2018-11-28 17:29:40] [CRITICAL] QQBOT 异常停止（code=203）

在配置里面修改掉线后自动重启为True
定时重启schedrestart插件也有运行

**Comment by pandolia** [comment]
qqbot -u somebody

**Comment by liang55** [comment]
我是这么启动的 qqbot.RunBot(['-u', 'somebody']) ，不一样吗

**Comment by pandolia** [comment]
那不行的。只能 qqbot -u somebody 。或者 python yourscript.py -u somebody 。
否则只有第一次掉线后会重启，第二次掉线后不会重启。
