### ISSUE TITLE
邮箱收不到验证码

### ISSUE THREAD

**Issue by MrsLi** [pandolia/qqbot#383]
邮箱的地址和SMP都设置了,运行程序的时候,邮箱收不到验证码,还有什么额外的设置吗?
我的代码:
# coding=utf-8
from qqbot import QQBotSlot as qqbotslot,RunBot
from model.model import Vod,DBSession

@qqbotslot
def onQQMessage(bot, contact, member, content):
    if bot.isMe(contact, member):
        print('This is me')
    else:
        if contact.ctype=='group' and contact.name=='机器人测试群':
                bot.SendTo(contact,content)

if __name__ == "__main__":
    RunBot()

**Comment by liang55** [comment]
RunBot(‘-u’,'你配置的用户')

**Comment by pandolia** [comment]
qqbot -u somebody
or
python yourscript.py -u somebody

**Comment by MrsLi** [comment]
明白了,没指定配置的用户
