### ISSUE TITLE
QQ号上好友和群太多的话要登入很久

### ISSUE THREAD

**Issue by 1323811540** [pandolia/qqbot#39]
能不能改改这个登入- -

**Comment by pandolia** [comment]
主要的时间耗在群资料的获取上了，如果群多的话确实很耗时间，一个群至少需要进行一次网页请求。
好在手动登录成功后，两天内可以自动登录，不需要再次获取好友和群资料，速度非常快。

**Comment by pandolia** [comment]
另外，最主要的时间是耗在 “获取好友和群的真实QQ” 上面了。如果不需要获取真实QQ，那可以去掉相关的代码，应该可以在30秒内完成登陆的。此时，尽管没有真实QQ，但好友和群的 uin 和 nickname 还是可以获取到的，可以通过这两个属性来选择需要的联系人。

**Comment by pandolia** [comment]
新 2.1.1 版修改了启动方式，登录成功后不获取任何联系人资料就启动 QQBot ，启动速度飞快，10~15秒可启动完毕。启动后再在后台获取联系人资料。
新版暂时放在 fix-fetch-problems 分支下：https://github.com/pandolia/qqbot/tree/fix-fetch-problems
