### ISSUE TITLE
做成服务器扫描的那种形式 如果多个QQ号在服务器上登录 因为ip都是用服务器ip 多个QQ号在同一个ip上登录被禁封怎么办  能不能加一个类似shadowsocks端口转发的选项或者插件 在用户那里安装一个shadowsock客户端 然后服务器这边以用户的ip操作他的那个QQBOT!!! 求解

### ISSUE THREAD

**Issue by crossfirewelove** [pandolia/qqbot#390]
做成服务器扫描的那种形式 如果多个QQ号在服务器上登录 因为ip都是用服务器ip 多个QQ号在同一个ip上登录被禁封怎么办  能不能加一个类似shadowsocks端口转发的选项或者插件 在用户那里安装一个shadowsock客户端 然后服务器这边以用户的ip操作他的那个QQBOT!!! 求解

**Comment by pandolia** [comment]
这个功能太复杂了，你可以研究一下。
