### ISSUE TITLE
请问一个或许与技术无关的问题,腾讯smartqq关闭服务后,是不是机器人就无法使用了？

### ISSUE THREAD

**Issue by help1234** [pandolia/qqbot#391]
刚刚了解这个项目，而且自己定义了插件让qq机器人完成一些日常的查询工作，不想就这么over啊

**Comment by pandolia** [comment]
是的，如果服务关了本项目就无法使用了。

**Comment by help1234** [comment]
这真是太可惜了,请问还有什么代替的方案吗？有没有驱动qq客户端的机器人呢？我在github搜索了没有发现有这样的项目

**Comment by Raka-loah** [comment]
> 这真是太可惜了,请问还有什么代替的方案吗？有没有驱动qq客户端的机器人呢？我在github搜索了没有发现有这样的项目

目前部分闭源的机器人有http接口功能，写给qqbot的插件可以通过flask-restful快速转换成http交互方式，算是曲线救国了。不过确实希望还有别的开源解决方案能用。

**Comment by Raka-loah** [comment]
> > > 这真是太可惜了,请问还有什么代替的方案吗？有没有驱动qq客户端的机器人呢？我在github搜索了没有发现有这样的项目
> > 
> > 
> > 目前部分闭源的机器人有http接口功能，写给qqbot的插件可以通过flask-restful快速转换成http交互方式，算是曲线救国了。不过确实希望还有别的开源解决方案能用。
> 
> 求推荐几个, 刚要开发这块内容.... 公司非得是QQ.

目前试了几个，比较方便的是酷Q，其HTTP插件有docker镜像一步到位，本地python用flask-restful做个最基础的带post的接口即可，之前写给qqbot的插件代码可以直接抄进去。
