### ISSUE TITLE
linux系统下不能获取二维码

### ISSUE THREAD

**Issue by yuxue0927** [pandolia/qqbot#4]
第一次联网返回数据显示二维码已失效

**Comment by pandolia** [comment]
您好，二维码失效时应该会自动重新获取新的二维码的。能否发一个 log 给我？

**Comment by yuxue0927** [comment]
：手动登录
%(levelname)s - qqbot.py[69]- 登录方式：手动登录
%(levelname)s - connectionpool.py[805]- Starting new HTTPS connection (1): ui.ptlogin2.qq.com
%(levelname)s - connectionpool.py[401]- "GET /cgi-bin/login?daid=164&target=self&style=16&mibao_css=m_webqq&appid=501004106&enable_qlogin=0&no_verifyimg=1&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html&f_url=loginerroralert&strong_login=1&login_state=10&t=20131024001 HTTP/1.1" 200 13086
<Response [200]>
%(levelname)s - connectionpool.py[805]- Starting new HTTPS connection (1): ssl.ptlogin2.qq.com
%(levelname)s - connectionpool.py[401]- "GET /ptqrlogin?webqq_type=10&remember_uin=1&login2qq=1&aid=501004106&u1=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&ptredirect=0&ptlang=2052&daid=164&from_ui=1&pttype=1&dumy=&fp=loginerroralert&action=0-0-1475794.4923161834&mibao_css=m_webqq&t=undefined&g=1&js_type=0&js_ver=10141&login_sig=&pt_randsalt=0 HTTP/1.1" 200 66
ptuiCB('65','0','','0','二维码已失效。(1611682120)', '');

[2016-08-13 00:22:56,842] [QQBot-v1.6.2 INFO] 登录 Step1 - 获取二维码
%(levelname)s - qqbot.py[150]- 登录 Step1 - 获取二维码
%(levelname)s - connectionpool.py[401]- "GET /ptqrshow?appid=501004106&e=0&l=M&s=5&d=72&v=4&t=0.79603527848499711 HTTP/1.1" 200 502
[2016-08-13 00:22:57,998] [QQBot-v1.6.2 WARNING]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/qqbot.py", line 160, in getQrcode
    showImage(self.qrcodePath)

**Comment by yuxue0927** [comment]
：手动登录
%(levelname)s - qqbot.py[69]- 登录方式：手动登录
%(levelname)s - connectionpool.py[805]- Starting new HTTPS connection (1): ui.ptlogin2.qq.com
%(levelname)s - connectionpool.py[401]- "GET /cgi-bin/login?daid=164&target=self&style=16&mibao_css=m_webqq&appid=501004106&enable_qlogin=0&no_verifyimg=1&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html&f_url=loginerroralert&strong_login=1&login_state=10&t=20131024001 HTTP/1.1" 200 13086
<Response [200]>
%(levelname)s - connectionpool.py[805]- Starting new HTTPS connection (1): ssl.ptlogin2.qq.com
%(levelname)s - connectionpool.py[401]- "GET /ptqrlogin?webqq_type=10&remember_uin=1&login2qq=1&aid=501004106&u1=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&ptredirect=0&ptlang=2052&daid=164&from_ui=1&pttype=1&dumy=&fp=loginerroralert&action=0-0-1475794.4923161834&mibao_css=m_webqq&t=undefined&g=1&js_type=0&js_ver=10141&login_sig=&pt_randsalt=0 HTTP/1.1" 200 66
ptuiCB('65','0','','0','二维码已失效。(1611682120)', '');

[2016-08-13 00:22:56,842] [QQBot-v1.6.2 INFO] 登录 Step1 - 获取二维码
%(levelname)s - qqbot.py[150]- 登录 Step1 - 获取二维码
%(levelname)s - connectionpool.py[401]- "GET /ptqrshow?appid=501004106&e=0&l=M&s=5&d=72&v=4&t=0.79603527848499711 HTTP/1.1" 200 502
[2016-08-13 00:22:57,998] [QQBot-v1.6.2 WARNING]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/qqbot.py", line 160, in getQrcode
    showImage(self.qrcodePath)

**Comment by pandolia** [comment]
谢谢！除了这个，后面应该可以正常登录了吧？
程序运行的最开始的一次确实是返回“二维码失效”，但从第二次开始就都是未失效的了。第一次是故意发送一个已失效的 cookie 给腾讯服务器，所以就返回“二维码已失效“。发送已失效的 cookie 可以退出上次的登录，避免本次登录错误。

**Comment by yuxue0927** [comment]
就是不能登录，获取二维码图片是损坏的
%(levelname)s - connectionpool.py[401]- "GET /ptqrshow?appid=501004106&e=0&l=M&s=5&d=72&v=4&t=0.79603527848499711 HTTP/1.1" 200 502
这里显示图片数据大小只有502字节，显然是不对的
[2016-08-13 00:22:57,998] [QQBot-v1.6.2 WARNING]
Traceback (most recent call last):
File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/qqbot.py", line 160, in getQrcode
showImage(self.qrcodePath)
这里报错内容是没有这个文件，没有二维码无法继续了

**Comment by pandolia** [comment]
汗，这个我还没看出问题在哪里，您看看单独运行下面这些代码能否获取到二维码图片：

    session = requests.Session()
    resp = session.get('https://ssl.ptlogin2.qq.com/ptqrshow?appid=501004106&e=0&l=M&s=5&d=72&v=4&t=0.79603527848499711‘)
    with open('qrcode.png', 'wb') as f:
        f.write(resp.content)

**Comment by yuxue0927** [comment]
又测试了下，改变目录可以获取二维码，确实不到500字节的小图片，开始应该是文件权限问题导致图片损坏所以看不出来

**Comment by pandolia** [comment]
文件权限问题倒是确实没考虑过，一般当前用户在他自己的 /home 目录下应该是都有读写权限的。准备在下一版中将以下代码：

    TmpDir = os.path.join(os.path.expanduser('~'), '.qqbot-tmp')
    if not os.path.exists(TmpDir):
        os.mkdir(TmpDir)

改为：

    try:
        TmpDir = os.path.join(os.path.expanduser('~'), '.qqbot-tmp')
        if not os.path.exists(TmpDir):
            os.mkdir(TmpDir)
        tmpfile = os.path.join(TmpDir, 'tmptest%f' % random.random())
        with open(tmpfile, 'w') as f:
            f.write('test')
        os.remove(tmpfile)
    except:
        TmpDir = os.getcwd()

如果在 /home/{user}/.qqobt-tmp 目录下读写失败了，则在直接在当前目录下保存二维码图片等文件。

您看看这样改了后是否可用？

**Comment by csrgxtu** [comment]
在mac下正常工作。
