### ISSUE TITLE
如何实现自动发送消息呢？

### ISSUE THREAD

**Issue by sspboy** [pandolia/qqbot#40]
没有接受到消息的情况下，如何定义自动发送消息呢

**Comment by pandolia** [comment]
可以注册一个 'polltimeout' 的回调函数，示例代码。

    @myqqbot.On('polltimeout')
    def handler(bot, message): 
        # 此时的 message.mtype 为 'polltimeout'
        pass

没有消息的情况下，上面这个回调函数每隔 1 分钟被调用一次。

本程序的运行方式：

程序目前采用 消息/响应 的方式运行，后台开启三个子线程，分别运行 pollForever 、 fetchForever 和 termServer.Run ，分别负责 QQ 消息轮询 、 联系人资料获取 和 qterm 客户端消息监听，子线程收到消息或完成联系人资料获取时，会向主线程发消息（实际是将一个 Message 对象放入一个消息队列中去）。主线程不停的从消息队列中取出消息，并根据消息类型调用相应的回调函数。所有对联系人资料的查询和更新等操作均在主线程中完成，避免了多个线程对同一个数据进行操作。

没有 “QQ消息“” 的情况下，每隔一分钟 pollForever 子线程会将一个 'polltimeout' 类型的消息放到消息队列中去。主线程从消息队列取出这种类型的消息时，会调用相应的回填函数（默认是一个空函数）。

**Comment by sspboy** [comment]
感谢回复。：）
