### ISSUE TITLE
QQ群里人发送的临时会话，qqbot没有反应？

### ISSUE THREAD

**Issue by ofooo** [pandolia/qqbot#41]
QQ群里的人发送的（私聊）临时会话，我们不是好友，就没法检测到这个聊天消息。
请问如何接收这种临时会话呢？

**Comment by pandolia** [comment]
在网页版 w.qq.com 上测试了一下，也收不到非好友的临时会话消息。所以没办法接收了，腾讯服务器没有将这种类型的消息转发给网页版登录的用户。
