### ISSUE TITLE
ImportError: cannot import name 'QQBot'

### ISSUE THREAD

**Issue by KennethYeah** [pandolia/qqbot#42]
我在ubuntu 16.04的服务器上运行，服务器里面同时又python3 和python2.7，安装了qqbot以后，启动时好像默认用python3打开了，所以才会error，这个怎么解决呢。

**Comment by pandolia** [comment]
可以下载所有源码后，再用 python2.7 运行 qqbot.py 文件。

**Comment by pandolia** [comment]
命令： python qqbot.py
