### ISSUE TITLE
运行一段时间qq群里面发消息就有问题啦

### ISSUE THREAD

**Issue by yuanaichi** [pandolia/qqbot#47]
从日志看 向 『xxx』群发送消息成功  但是群里面没有消息

这时候给好友发送消息是成功的 

是不是 群的某些属性会变？

**Comment by pandolia** [comment]
我测试一下看看。

**Comment by yuanaichi** [comment]
我把 pickle文件删除了 重新登录 没有问题了暂时  这个问题 出现了几次了

**Comment by pandolia** [comment]
我这边试了一下，运行了10个小时了还是可以发群消息。可能只是偶尔会出现这个问题。你试下把 qsession.py 文件中 smartRequest 方法中 “if retcode in (0, 6, 1202, 100003, 100100):” 的 1202 去掉，看看能不能正常发消息。

**Comment by yuanaichi** [comment]
好的 谢谢 我试试

**Comment by nntaoli** [comment]
@yuanaichi  这个问题，我觉得可以这样解决：在发送完消息后，再去查询监听QQ群消息，是否收到这条消息，如果未收到，可能就是没发送成功，没成功就可以清空缓存，重新获取群属性在发送一次消息。

**Comment by pandolia** [comment]
@nntaoli 关键是自己发的信息是收不到的。。。只能收到别人发的信息。

**Comment by qqdaiyu55** [comment]
这个问题确实经常出现。运行一段时间后，私聊发送成功但无法发到群聊中(虽然日志显示发送成功)。每次都得重启才行

**Comment by pandolia** [comment]
去掉 1202 的 retcode 有没有效果？

**Comment by pandolia** [comment]
这个问题怀疑和后台运行了 fetchforever 有关，可能运行一段时间后，后台获取到了错误的 uin ，所以发送至错误的群里面去了，但是日志还是显示发送成功。现在的 2.0.8 版去掉了 “在后台获取联系人资料” 的功能，请大家帮忙测试一下，看看最新版还有没有这个问题。

**Comment by yuanaichi** [comment]
去掉 1202 后 没有再出现这个 问题 不知道有没有关系 ，  我更新到 2.0.8 试试

**Comment by yuanaichi** [comment]
pip没有更新到 2.0.8 最新的2.0.7

**Comment by pandolia** [comment]
现在应该已经更新到 2.0.9 了。如果 pip install qqbot 还是安装 2.0.7 版。可以下载源码后 cd 到源码目录并运行 "pip install ." 。

**Comment by qqdaiyu55** [comment]
实测 2.0.9 依旧出现这个问题

**Comment by pandolia** [comment]
2.0.9 还是保留了 1202 retcode 。看来问题不在于 fetchforever ，还是在 1202 这里。准备下一版中去掉 12 02。

**Comment by yuanaichi** [comment]
@pandolia 确实还是有问题  之前去了1202 没有问题

**Comment by pandolia** [comment]
现在2.0.10已经去掉了1202。
