### ISSUE TITLE
add python 3 support

### ISSUE THREAD

**Issue by chenhouwu** [pandolia/qqbot#48]
please support python 3.
it should be easy.
see: http://python-future.org/

**Comment by pandolia** [comment]
谢谢！我尽快增加对 python3 的支持。

**Comment by pandolia** [comment]
python3 的测试版见 https://github.com/pandolia/qqbot/tree/py3 。

**Comment by pandolia** [comment]
欢迎试用，有问题请发到 https://github.com/pandolia/qqbot/issues/61

**Comment by pandolia** [comment]
最新的 2.0.12 版已支持python3，可使用 pip 或 pip3 安装。
