### ISSUE TITLE
运行了几十分钟后，无法获取群成员昵称，全部是UNKNOWN了

### ISSUE THREAD

**Issue by nntaoli** [pandolia/qqbot#50]

**Comment by pandolia** [comment]
重新登录一次吧。或者等 5 分钟，后台会重新获取一次所有联系人资料。
最近获取联系人资料开始出问题，可能腾讯又在协议上动手脚了。可以把 qqbot.py 文件第 33 行 “self.AddGenerator(self.fetchForever)” 注释掉，停止在后台获取联系人资料。这样就不会运行几十分钟后群成员的昵称被修改为 UNKNOWN 。
