### ISSUE TITLE
linux下二维码支持在shell中弹出

### ISSUE THREAD

**Issue by fanlushuai** [pandolia/qqbot#51]

**Comment by pandolia** [comment]
这个没啥必要吧。linux下如果有GNOME桌面环境，会自动调用 gvfs-open 或 shotwell 打开图片。或者如果您是别的桌面环境，你可以告诉我你的系统中打开图片的默认程序，我可以增加相应的代码。
如果是纯终端系统，可以使用服务器模式或邮箱模式打开二维码。邮箱模式还是很方便的。
在shell中显示二维码，需要增加对 PIL 等图片库的依赖，在有些系统中可能有无法安装或安装冲突的问题。

**Comment by tetsaicn** [comment]
转换成字符呗
