### ISSUE TITLE
xml结构化信息发送

### ISSUE THREAD

**Issue by qqdaiyu55** [pandolia/qqbot#52]
支持xml信息的发送吗(会解析为卡片的)，还是说smartqq不支持？

**Comment by pandolia** [comment]
具体什么样的信息？我试一下看看

**Comment by qqdaiyu55** [comment]
Example:
```
<?xml version="1.0" encoding="utf-8"?>
<msg templateID="12345" action="web" brief="TEST" serviceID="1" url="http://koukuko.com">
    <item layout="1">
        <title>layout="1"</title>
        <summary>title,summary,picture各占一行均可重复使用，按照Element顺序显示</summary>
        <picture cover="http://placekitten.com/250/100"/>
    </item>
</msg>
```
Preview:
[Image](https://camo.githubusercontent.com/08cc3f008944aad6240be9b1bf268d14a98ea130/687474703a2f2f7777342e73696e61696d672e636e2f6c617267652f373764373337336467773166327179767773306a656a323039743036756d78702e6a7067)

**Comment by pandolia** [comment]
写了个脚本测试了一下：

    s = '''\
    <?xml version="1.0" encoding="utf-8"?>
    <msg templateID="12345" action="web" brief="TEST" serviceID="1" url="http://koukuko.com">
        <item layout="1">
            <title>layout="1"</title>
            <summary>title,summary,picture各占一行均可重复使用，按照Element顺序显示</summary>
            <picture cover="http://placekitten.com/250/100"/>
        </item>
    </msg>\
    '''
    
    from qqbot import QQBot
    bot = QQBot()
    bot.Login()
    bot.Send('buddy', 'Jack', s)

这时 Jack 收到的是一段文本。效果是下面这样的：

![qq 20170223215257](https://cloud.githubusercontent.com/assets/13767061/23261696/7f374870-fa12-11e6-9a15-4fda5d31560d.png)

**Comment by pandolia** [comment]
貌似发不了， xml 应该还需要进一步处理之后再发送，这样才能在对方的 qq 客户端上被显示为卡片消息。就是不知道这种卡片消息的具体格式是怎么样的。

**Comment by qqdaiyu55** [comment]
是的，单纯文本方式发送不出来的，要经过协议层的处理，格式可以参考[QQ的XML消息格式整理](https://gist.github.com/koukuko/eb375cee7883764e01fb213b1ace4727)

**Comment by pandolia** [comment]
那个链接我看了一下，讲的还是xml的结构，没有讲消息的底层格式。
可能 smartqq 协议只能发文本消息。
