### ISSUE TITLE
登录成功后读取好友和群列表中id有缓存

### ISSUE THREAD

**Issue by xiaonieya** [pandolia/qqbot#55]
比如手机QQ登录，加载好友列表：A｛uin:1111,name:好友A｝B｛uin:2222,name:好友B｝
但是程序放到云服务上，服务器跟手机网络不在同一地方，启动时加载的可能就会是
A｛uin:3333,name:好友A｝B｛uin:4444,name:好友B｝

如果要给某好友发送消息，根据名称找到的uin是3333、4444发消息发不到实际的QQ号，服务器上的重登陆都不会刷新uin，一直都是3333、4444，此时如果指定给uin1111发消息，好友A可以正常收到消息，而3333却不行。

请问该项目是否有该情况，谢谢！

**Comment by pandolia** [comment]
抱歉，我没看懂您说的到底是什么情况。
你在服务器上使用本程序登录，如果获取到好友 A 的 uin 是 3333，那你向 uin3333 发消息，好友 A 会收到的消息的。
如果你同时在两个地方用本程序登录同一个 qq ，那可能有一个机器上的 qq 会掉线。

**Comment by xiaonieya** [comment]
sorry  我再描述下。

1、服务器是用本程序登录，此时应该是smartqq方式，另外一个是手机qq，2者同时不会掉线
2、此时直接给uin3333发消息，好友A收不到消息，但好友A给本程序发消息，日志显示uin是1111
3、此时再直接给uin1111发消息，好友A就收的到消息，但此时程序重新加载好友列表，好友A的uin还是3333

现象测试：本机PC（广东IP）启动本程序，好友A的uin是1111，关闭本机PC，云服务器（北京IP）启动则是3333，再关闭云服务器，本机PC启动则是1111，不论来回几次。

**Comment by pandolia** [comment]
服务器上删除掉 /home/user/.qqbot-tmp 下的 pickle 文件再重新登录一下试试。

**Comment by pandolia** [comment]
也有可能是你同时用服务器和本地机器同时使用本程序登录同一个qq的原因。
