### ISSUE TITLE
目前发现群消息中，对方如果不是机器人好友的话，获取不到对方的qq号吗

### ISSUE THREAD

**Issue by igmpxb** [pandolia/qqbot#57]
收到消息后调用get方法 返回的列表为0，但是uin可以被打印出来
contact=bot.Get('buddy',uin=msg.memberUin)
            numer=len(contact)
            if numer==0:
                print "yyyyyyyyyy"

**Comment by pandolia** [comment]
是的。协议不支持获取群内非好友的 qq 。你可以登陆 w.qq.com 测试一下，如果不是好友的话，看不到对方的 qq 号。

**Comment by pandolia** [comment]
前天测试了一下，那个get_friend_uin2可以获得群内非好友的qq。我会尽快增加此功能。

**Comment by pandolia** [comment]
新的 2.1.1 版已增加获取非好友 qq 的功能，新版暂时放在 fix-fetch-problems 分支下：
https://github.com/pandolia/qqbot/tree/fix-fetch-problems
