### ISSUE TITLE
不支持@功能吗？

### ISSUE THREAD

**Issue by shangguan1997** [pandolia/qqbot#58]

**Comment by pandolia** [comment]
暂时不支持。后续版本中再增加吧。

**Comment by shangguan1997** [comment]
恩恩，希望可以对群功能进行强化，比如或取群名片什么的。
再次表示感谢！

**Comment by yuanaichi** [comment]
@ 我获取到的message content 就是正常的文本 没有什么特殊的 我现在自己 做了match

**Comment by pandolia** [comment]
在 w.qq.com 上测试了一下，不能 @ 别人，比方说群内另一个成员 “小明” ，在网页上发送 “@小明 你好" ，这时小明是只能收到这个文本信息，没有被 @ 的通知。这和用 PC qq 或 手机 qq 上 @小明 的效果是不同的。所以本程序也不能 @ 别人了。。。
”了解是否被别人 @ “ 可以按 @yuanaichi 的方式来处理，如果 @ 后面的名字刚好是自己的群名片，则可以知道自己被别人 @ 了。

**Comment by shangguan1997** [comment]
似乎无法获取群名片啊

**Comment by pandolia** [comment]
最新的 2.1.1 版已增加 @ 的通知，且可以获取群成员的名片。
