### ISSUE TITLE
QQBot 命令格式错误

### ISSUE THREAD

**Issue by laolai** [pandolia/qqbot#64]
qq list group
QQBot 命令格式错误

![image](https://cloud.githubusercontent.com/assets/3068867/23736508/8edb62b0-04c7-11e7-8861-1dbf9bc09195.png)

这是什么情况，跟buddy相关的命令都能成功，跟group相关的都不行，我打的命令不对？

**Comment by pandolia** [comment]
可能是登录时没有获取到群列表。restart 一下看看

**Comment by laolai** [comment]
重启一下果然OK了

**Comment by pandolia** [comment]
2.1.1 版中应该不会有这个问题了，暂时在 fix-fetch-problems 分支下：
https://github.com/pandolia/qqbot/tree/fix-fetch-problems
