### ISSUE TITLE
有办法发图片和获取群新进人事件吗？

### ISSUE THREAD

**Issue by mo10** [pandolia/qqbot#66]
有办法发图片和获取群新进人事件吗？
好像不可以发起临时聊天，只能加好友才能给对方发消息？

**Comment by pandolia** [comment]
图片发不了，临时聊天好像也不行。
新人事件的功能我这两天正在增加。

**Comment by mo10** [comment]
加油:)

**Comment by pandolia** [comment]
新人事件的功能将在 2.1.1 版中增加，暂时放在 fix-fetch-problems 分支下：
https://github.com/pandolia/qqbot/tree/fix-fetch-problems
