### ISSUE TITLE
SmartQQ现在不太稳定，poll总是504超时，难道腾讯要放弃了？

### ISSUE THREAD

**Issue by pengqi** [pandolia/qqbot#70]
如题。

**Comment by pandolia** [comment]
poll时504超时没关系, 直接忽略就可以了. 
当没有未读消息时, poll 阻塞1分钟然后返回504错误. 在本程序中,此时会调用 BasicAi.onPollTimeout 方法.

**Comment by pengqi** [comment]
有关系，测试发现会造成大量消息丢失。

**Comment by pandolia** [comment]
这几天好像没问题了。
