### ISSUE TITLE
好像掉线自动重新登录没有用?

### ISSUE THREAD

**Issue by 279632990** [pandolia/qqbot#72]
登录一天左右就会掉线,选择的邮箱接收登录二维码,但是我第二天看服务器的进程,好像掉线程序就退出了

**Comment by pandolia** [comment]
我测试一下。

**Comment by pandolia** [comment]
看了一下，qqbotcls.py 文件里面的这一段写的是有问题：

            while True:
                code = subprocess.call(args)
                if code == 0:
                    break
                elif code == QSESSION_ERROR:
                    if self.conf.restartOnOffline:
                        args[-2] = self.conf.qq
                        INFO('重新启动 QQBot ')
                    else:
                        break
                elif code == RESTART:
                    args[-2] = ''
                    INFO('重新启动 QQBot （手工登陆）')
                else:
                    break

只有当退出码是 QSESSION_ERROR 时才会重启，我以为退出码除了 (0, QSESSION_ERROR, RESTART) ，其他情况都不会出现。。。因为之前掉线时的退出码就是 QSESSION_ERROR 。
先把程序改成下面这样吧，这样应该可以了：

            while True:
                code = subprocess.call(args)
                if code == 0:
                    break
                elif code == RESTART:
                    args[-2] = ''
                    INFO('重新启动 QQBot （手工登陆）')
                elif self.conf.restartOnOffline:
                    args[-2] = self.conf.qq
                    INFO('重新启动 QQBot ')
                else:
                    break

另外要确保自动重启模式已经打开。

**Comment by 279632990** [comment]
恩 自动重启设置为true了,我去试试

**Comment by pandolia** [comment]
这个 bug 将在 2.1.1 版中修正，暂时放在 fix-fetch-problems 分支下：
https://github.com/pandolia/qqbot/tree/fix-fetch-problems
