### ISSUE TITLE
新版 2.1.1 版已发布，再次进行重构，功能加强，启动速度飞快，运行更加稳定，接口不再兼容 2.0 版

### ISSUE THREAD

**Issue by pandolia** [pandolia/qqbot#74]
本次 2.1 版在 2.0 版的基础上再次进行大量的重构，功能加强，运行更加稳定，修正了几个 bug ，但不再兼容 2.0 版的接口。

对于已使用 2.0 版开发了自己的 QQBot 机器人的网友，很抱歉本次修改给你们带来了小小的麻烦，您需要稍微修改一下自己的程序了。但本次升级几乎有了质的飞跃，所有迁移过来还是好处多多的。 ^_^ 

主要功能加强和 bug 修正如下：

1） 联系人资料获取和查询功能加强，可获取到联系人的 QQ号/昵称/名称/备注名/群名片 。群内非好友的 QQ 号也可以获取到。
2） 联系人资料实时更新，增加 新增/失去 联系人的事件通知，增加被群内其他成员 @ 的通知。
3） 将启动速度加快到极致， 扫码后 10 ~ 15 秒可启动 QQBot 。 2.0 版需要获取完所有联系人资料才会启动 QQBot ，新版登陆成功后立即启动 QQBot ，同时在后台开始获取联系人资料。当联系人资料获取尚未全部完成时收到 QQ 消息或 list/send 命令，会主动获取所需的联系人资料，因此 QQBot 刚启动时收到新消息或 list/send 命令会稍微卡顿 1~2 秒。
4） 修正联系人资料获取中的 bug ，联系人资料获取更加稳定；修正程序掉线时有时无法自动重启的 bug ；修正 windows 下用某些图片浏览器弹出二维码后程序一直卡在等待图片窗口关闭的 bug 。
5） 修改 qq 命令行工具的命令及格式，去掉 2.0 版的 get 和 member 命令，新的 list 命令提供强大的联系人查询功能。

对于已使用 2.0 版开发了自己的 QQBot 机器人的网友，请注意以下接口的改变和新增的事件：

6） 修改 QQBot 对象的接口，去掉原来的 Get/Member/Send 接口，只保留 List/SendTo/Stop/Restart 四个接口，新的 List 接口功能更加强大，且参数的格式更简洁、明了。
7） 修改 注册事件响应函数 的格式，修改注册 QQ 消息响应函数的格式，新的格式更简洁、明了。
8） 增加 新增/失去联系人 事件，可注册这两个事件的响应函数，实现 新人入群/退群 的通知功能。
9） 增加 Interval 事件，每隔 5 分钟被调用，可注册此事件的响应函数，实现定时执行任务的功能。
10） 原有的配置文件 ~/.qqbot-tmp/v2.0.conf 需要重命名为 ~/.qqbot-tmp/v2.1.conf 。文件内容无需改变。

对于已改写过本项目内部源码的网友（不清楚是否有人这样做），请注意：

11） 程序的内部运行方式和数据结构有较大改变。重点关注  qqbotcls.py， mainloop.py，qslots.py， qssession.py  和 qcontactdb.py 五个文件，程序的主体运行流程见 mainloop.py ，用非常简单和优雅的方式解决了多任务并行和数据同步的问题。

非常感谢以下网友在本次升级过程的帮助和支持：

@sjdy521 提供了 ”使用 qun.qq.com 的 api 获取联系人实际 QQ ” 的宝贵建议，另外本次新版的 QQBot 启动方式也受到了他的项目的启发。
@bolfhsu 提出 ”List与Get功能重复、Get应该是获取消息“ 的意见。原版中的 Get 接口很容易让人误解为 ”获取消息“ ，虽然我的本意是 ”获取联系人“ ，本次去掉了 Get 接口，将其功能合并到 List 接口中。
@279632990 和 Moofeng 反馈了 ”程序掉线时有时无法自动重启“ 的 bug 。
阿兰若 和 怪我瞎咯 反馈了 ”windows 下用某些图片浏览器弹出二维码后程序一直卡在等待图片窗口关闭的 bug “。

新版使用过程中有任何问题请回复在本 issue 下面。

**Comment by pandolia** [comment]
python3 下暂未测试，由于程序已尽量按 2 和 3 兼容的格式编写，应该是不需要怎么改动的。

**Comment by 1323811540** [comment]
哇 太棒了，我之前就是这么想得，登录上后 后台获取。这样我就可以登我1000+联系人..200+群的QQ了^_^

**Comment by y85171642** [comment]
简直棒极，今天突然看到这个，好兴奋~
