### ISSUE TITLE
获取不到好友

### ISSUE THREAD

**Issue by y85171642** [pandolia/qqbot#75]
CRITICAL] 第3次请求“http://s.web2.qq.com/api/get_friend_info2”时出现 请求被拒绝错误，html='{"retcode":100000}'

**Comment by y85171642** [comment]
问题大概是：
机器人QQ选择允许所有人加好友，
其他QQ添加机器人好友后，可以直接发消息了，但是此时机器人还没有添加此人，导致的问题，

**Comment by pandolia** [comment]
哦，有可能，当机器人收到一条好友消息时，先在联系人数据库中搜索是否有这个好友、进而得到好友的详细资料（qq号、昵称等），如果搜索不到，会请求 http://s.web2.qq.com/api/get_friend_info2 来获取好友的详细资料。没想到有些情况下会出错。
但是即便出现这个错误，没有引起整个程序的崩溃吧？应该会显示： 来自 好友“##UNKOWN”的消息... 。
过几分钟等后台又整个刷新了一遍联系人数据库后应该就正常了。

**Comment by y85171642** [comment]
是的，老铁没毛病

**Comment by y85171642** [comment]
发现个问题，更新[群|好友|讨论组]列表 时候，onQQMessage收不到消息，

**Comment by pandolia** [comment]
是卡顿了一下，过一会才有消息。还是那条消息就没收到？

**Comment by y85171642** [comment]
我仔细测试一下

**Comment by y85171642** [comment]
有好友请求，确认添加的接口吗？
不然需要在PC端，加一次好友，才能变成好友，即使开了允许所有人添加好友

**Comment by y85171642** [comment]
确定了，在更新列表的时候，是收不到消息的~不是延迟

**Comment by pandolia** [comment]
![qq 20170321230812](https://cloud.githubusercontent.com/assets/13767061/24154141/4a53ff9e-0e8b-11e7-8b3d-8953f3966338.png)
不知道怎么回事。。。我这边更新的时候是可以收到消息的。是不是临时会话消息？

**Comment by pandolia** [comment]
实在不行，你看看把 qcontactdb.py 文件第 264 行：

     time.sleep(120 if tinfo == 'end' else 5)

最后数字 “5” 改大一点，让更新一个列表后的间隔时间大一些。看看能不能收到消息。

**Comment by pandolia** [comment]
好友请求、确认添加的接口应该是没有，你可以在网页版 w.qq.com 看一下，没有这样的接口。

**Comment by y85171642** [comment]
明白了，多谢解答~辛苦了

**Comment by pandolia** [comment]
你提的这个请求错误的问题，不知道这样改能不能解决问题：当在联系人数据库内没能找到好友时，不向  http://s.web2.qq.com/api/get_friend_info2 请求数据了，而是立即请求并刷新一次整个好友列表。

要改其实也非常简单，把 qcontactdb.py 中第 163 行的：  “if tinfo == 'buddy':“ 改为： “if False:“ 就可以了。
你可以尝试一下，看看有没有效果。

**Comment by y85171642** [comment]
好的，明白~

**Comment by y85171642** [comment]
那个 更新列表卡的问题，还是存在。
我是在Mac上运行的项目，不清楚是不是mac网络阻塞之类的东西导致的，
我明天试试windows下什么情况！休息了~晚安~

**Comment by myuanz** [comment]
@y85171642 啊哦  才看到这里你也提了问题。window64也有类似问题

**Comment by myuanz** [comment]
可能是由于群人数的原因，因为我只加了一个1.8k/2k群，只会在那个2k群卡到，其余群群成员获取正常。
Ctrl+C 可临时解决

**Comment by myuanz** [comment]
刚准备改qcontactdb.py，才发现问题莫名其妙解决了。
我的问题总共只在前4次出现，之后就再没出现了。
大概是服务器问题吧，谁拿v-2.0测一下？

**Comment by myuanz** [comment]
我是手贱吗？QAQ
问题再一次复现了，还是那个大群
晚安\大概吧

**Comment by myuanz** [comment]
qcontactdb.py 中第 163 行的： “if tinfo == 'buddy':“ 改为： “if False:“ 之后又测试了3次，没问题了
晚安\这次一定！

**Comment by pandolia** [comment]
阻塞的问题不知道是不是因为群人数太多，卡在向任务队列里添加任务的那一步。按Ctrl+C可能刚好把添加任务那个动作取消了。能否把你按Ctrl+C后打印的那些信息发一下？

**Comment by pandolia** [comment]
“if tinfo == 'buddy':“ 改为： “if False:“ 不是为了解决阻塞的。是为了解决 y85171642 提到的获取新加好友（但是还没有在PC-QQ客户端上通过验证的好友）的资料失败的问题。

**Comment by myuanz** [comment]
我记得提示大致只有群成员获取失败，其他的我暂时手边没电脑没法弄

**Comment by pandolia** [comment]
好的。方便的话可以把我的小号 3497303033 加到那个大群里面去，我测试一下。

**Comment by myuanz** [comment]
那是个私有内部群。
还是等等楼上那位吧，非常抱歉

**Comment by y85171642** [comment]
> 实在不行，你看看把 qcontactdb.py 文件第 264 行：
 time.sleep(120 if tinfo == 'end' else 5)
最后数字 “5” 改大一点，让更新一个列表后的间隔时间大一些。看看能不能收到消息。

按照这个改成 20 试了下，问题出现的频繁度降低了，我估计改的再大一些，应该就好了。
可能是任务对立那里实现有点问题，我没仔细看
@pandolia @myuanz

**Comment by myuanz** [comment]
是了，我想起来了，就算是取消当前任务过一会还会出问题，你把作者小号拉进群吧，就在你楼上 @y85171642 

>

**Comment by myuanz** [comment]
> myuanz

**Comment by myuanz** [comment]
>

**Comment by SuperMarioSF** [comment]
关于后台刷新成员数据库的这个机制，不知道能否提供一个选项来避免后台刷新（也就是**刷新完才正式启动**的功能）。
此外，如果能够有一个启动后的事件和一个数据刷新完毕的事件的话，对后续的机器人程序的编写也有好处。

**Comment by pandolia** [comment]
@SuperMarioSF 可以的。可以再加两个可注册的slot： onLoginComplete 和 onFetchComplete 。

**Comment by pandolia** [comment]
@SuperMarioSF v2.1.4 版已增加了两个 slot ： onStartupComplete 和 onFetchComplete 。另外增加一个选项 -fi,--fetchInterval ，用来设置每轮联系人列表刷新之间的间隙时间，如果设置为 -1 ，则只会进行一次联系人列表获取。

**Comment by pandolia** [comment]
@myuanz @y85171642 刷新联系人列表卡顿应该耐心等待个 30 ~ 60 秒就好了，主要是卡在获取群组成员的真实 qq 那一步了，需要不停的对比 w.qq.com 和 qun.qq.com 两个接口返回的数据。后面联系人列表全部都下载完毕之后应该就不会再卡顿了。你们再试试。

**Comment by pandolia** [comment]
@myuanz @y85171642 v2.1.8版已彻底解决卡死的问题。速度飞快。实测1800人群的成员列表实际获取时间 2 ~ 3 秒。
