### ISSUE TITLE
可以增加一个 Interval 配置吗?

### ISSUE THREAD

**Issue by jim4node** [pandolia/qqbot#78]
我需要 08:07 自动向班级群发送 "起床啦", 9:03 发送"上课啦", 11:25 发送"准备吃饭"...
目前 onInterval 默认的 5分钟的间隔不满足我这个需求, 
所以建议在 conf 里增加一个 interval 设置, 单位为 1秒 就可以

**Comment by pandolia** [comment]
后面版本中我再考虑一下怎么加强 interval 的功能吧。
你可以先把 qqbotcls.py 中第160行 time.sleep(300) 改一下，改成 60 差不多可以满足你的要求。

**Comment by shangguan1997** [comment]
onInterval只提供了一个bot对象 @jim4node 你是怎么发送的消息那

**Comment by pandolia** [comment]
先用 List 找到想要的联系人对象啊。

**Comment by jim4node** [comment]
谢谢, 原先我自己找到这个 time.sleep(300) 改了, 希望在官方版本中 及时增加 Interval 设置

**Comment by pandolia** [comment]
@jim4node v2.1.12版增加的 QQBotSched 功能很强大了，你可以试试。见： https://github.com/pandolia/qqbot#%E5%AE%9A%E5%88%B6%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1
