### ISSUE TITLE
怎么发送换行消息

### ISSUE THREAD

**Issue by lvsenlin** [pandolia/qqbot#79]
如题

**Comment by pandolia** [comment]
SendTo 接口时可以发送换行消息的。 send 命令暂时还不行，我会在下一版本中修改一下，使 send 命令也可以发换行消息。
你也可以自己先修改一下 qslots.py 文件中的 cmd_send 函数，第109~110行改为：

    message = ' '.join(args[2:]).decode('string-escape')
    return '\n'.join(bot.SendTo(c, message) for c in cl)

这样就可以用“\n”代表换行，如：  send buddy jack 第一行\n第二行

**Comment by lvsenlin** [comment]
thank you

**Comment by pandolia** [comment]
刚才说的那个只适用于 python2。
python3 要用：
message = bytes(' '.join(args[2:]), 'utf8').decode('unicode_escape')

**Comment by pandolia** [comment]
刚才说的不适用于python3。

**Comment by pandolia** [comment]
刚才在 python3 下折腾了一下 string-escape ，不是 decode error 就是中文输出乱码，tnnd 。
就搞简单的替换好了，改成下面就可以了：

    msg = ' '.join(args[2:]).replace('\\n','\n').replace('\\t','\t')
    return '\n'.join(bot.SendTo(c, msg) for c in cl)

反正其他转义字符应该也没人会用到。
