### ISSUE TITLE
进入一个选项后要在这个选项中的分类在选一个可以实现吗？

### ISSUE THREAD

**Issue by NightKings** [pandolia/qqbot#80]

**Comment by pandolia** [comment]
可是可以，但感觉必要性不大。你可以用命令行选项来覆盖配置文件中的选项。

**Comment by pandolia** [comment]
比方说配置文件中 debug 选项为 True ，你可以在命令行中输入 -nd 来覆盖这个。

**Comment by NightKings** [comment]
额，我的意思是当一个用户在qq窗口输入一个选项后，机器人会在等待用户输入第二个选项，第二个选项包含在第一个菜单中
例如
`if content == '菜单'
     bot.SentTo(contact,‘1.xxx，2.xxx’)
`
在这之后用户在进行输入1或者2,再进行下面的选项要怎么实现呢，谢谢

**Comment by pandolia** [comment]
这个就要你自己用代码去实现了。

**Comment by pandolia** [comment]
你得用一个全局变量来保存上一条消息的内容，状态等信息。

**Comment by NightKings** [comment]
好的，谢谢了。
