### ISSUE TITLE
部分群成员名片获取失败

### ISSUE THREAD

**Issue by yzgyyang** [pandolia/qqbot#83]
QContact.card() 对于群内特定成员返回None，导致QContact.name()返回昵称而非群名片。这些成员同样设置了群名片。不太清楚解决思路。
![qq 20170328204311](https://cloud.githubusercontent.com/assets/16748524/24433505/31718ea8-13f7-11e7-865f-ab356b62d1f2.png)

**Comment by pandolia** [comment]
@yzgyyang 2.1.7版已经修复了。你重新用pip安装一下吧。

**Comment by yzgyyang** [comment]
非常感谢！版本迭代非常快，希望以后也可以多做些贡献。
