### ISSUE TITLE
登录时不再弹出本地 QRCode 窗口了

### ISSUE THREAD

**Issue by jim4node** [pandolia/qqbot#86]
以前都是本地窗口弹出 QRCode 的, 但好像是从 v2.1.4 的大升级开始就不弹出本地 QRCode 窗口了, 只得 http 打开, 不知何故.
QQBot v2.1.8, Win7-64bit, Python 2.7.13

**Comment by pandolia** [comment]
设置了 http 或邮箱模式就关闭了自动弹出了。

**Comment by pandolia** [comment]
关掉 http 和邮箱模式。才会自动弹图片。

**Comment by pandolia** [comment]
主要是考虑到设置了两项一般都是远程扫码的。如果也弹窗，可能会弹出好多窗口（如果没有及时扫码的话）。

**Comment by jim4node** [comment]
原来如此! 谢谢答复! 那么 我看有个文本 QRCode 的 pull request 不知为啥不 merge?
