### ISSUE TITLE
发送表情功能

### ISSUE THREAD

**Issue by bearqq** [pandolia/qqbot#9]
文档中没有发现发送表情功能的相关描述，看了看源码，抓了一下包，想和作者讨论一下。

群里有人发 /抠鼻 （请自信脑补抠鼻表情0.0）表情时，日志是
[face98]

在网页的smartqq发送 /抠鼻123 ，抓包如下：
{"to":11111111,"content":"[[\"face\",98],\" 123\",[\"font\",{\"name\":\"宋体\",\"size\":10,\"style\":[0,0,0],\"color\":\"000000\"}]]","face":0,
后面省略一些东西。

可以看到，表情是 ["face",98] 形式，查看源码后，将 msg=["face",98] 填入send中，成功发送表情。

但是如果要发送表情加上文字感觉就比较麻烦了，字典中"content"是一个list，末位是font的list，前面都是发送的内容，而按照目前源码中的实现的话，如何实现表情和文字的同时发送？
如果修改源码肯定可以实现这个功能，不过没有想到比较优雅的向后兼容的实现方式。

**Comment by sjdy521** [comment]
我是这样设计的，发送文本消息：
“你在干嘛[抠鼻]，都不回我”
这里的表情采用中括号的方式体现，程序自动检测文本中的支持的表情，转为最终的face代码

**Comment by bearqq** [comment]
也许像 “你在干嘛[face98]，都不回我” 这样更好，这样表情和message里的表述一样了。组装的时候再转换成list。
当然，如果有个字典类似{"抠鼻":"98"}这样也好，只是感觉需要手动做的事不少。。

**Comment by sjdy521** [comment]
不明白为什么会有这么奇怪的想法，作为一个使用者face98是什么东西？要发个表情难道我还需要知道对应什么编号？虽说是个小项目，但最基本的“产品用户体验”还是得注意下吧…

**Comment by bearqq** [comment]
那你把message里的face98也换了吧。
我是把这个接入神经网络，接受到的就是face98，发出去就发face98，没什么问题。
我不认为接收到face98却要求发送[抠鼻]是个好主意。因为这样你连echo机器人都写不出来。

**Comment by sjdy521** [comment]
好像咱俩讨论的不是一个层面的东西，底层的接收和发送肯定用face代码，但是上层的接口可以被这些内部细节隐藏掉不应该暴露给使用者


发自网易邮箱大师
在2016年09月25日 14:32，bearqq 写道:

那你把message里的face98也换了吧。
我是把这个接入神经网络，接受到的就是face98，发出去就发face98，没什么问题。
我不认为接收到face98却要求发送[抠鼻]是个好主意。因为这样你连echo机器人都写不出来。

**Comment by bearqq** [comment]
我想表述的就是message和send要里一致，没什么奇怪不奇怪的。
一个框架要做多复杂，暴露哪些东西是作者的事，我就不掺乎讨论了。

**Comment by pandolia** [comment]
我也觉得用文字应该好一点。底层发送也应该用文字，只有到最后一步发送到QQ服务器是才转换成face代码。不过这样得先有一个 “代码--文字” 的字典。

**Comment by sjdy521** [comment]
可以参考下我整理过的
https://github.com/sjdy521/Mojo-Webqq/blob/master/lib/Mojo/Webqq/Message/Face.pm



发自网易邮箱大师
在2016年09月25日 21:22，pandolia 写道:

我也觉得用文字应该好一点。底层发送也应该用文字，只有到最后一步发送到QQ服务器是才转换成face代码。不过这样得先有一个 “代码--文字” 的字典。

**Comment by pandolia** [comment]
v2.1.4版已增加表情发送和接收功能。再次感谢 sjdy521 精心制作的表情-代码表。

**Comment by pandolia** [comment]
@sjdy521 有网友在您整理的表情代码基础上进行了补充和完善，可参见：https://github.com/pandolia/qqbot/blob/master/qqbot/facemap.py

**Comment by sjdy521** [comment]
非常感谢 我加入到自己项目中
