### ISSUE TITLE
2.1.10已发布，增加 “需要特别监视的列表（ monitorTables ）” 的选项，大幅缩短群成员变动通知的滞后时间

### ISSUE THREAD

**Issue by pandolia** [pandolia/qqbot#90]
增加 “需要特别监视的列表（ monitorTables ）” 的选项，将需要关心的群加入到此项中，此群中的成员变动通知的滞后时间可以大幅缩短（最好的情况下可以缩短至 1~3 秒）。

v2.1.9 的修改：
1） 增加 “联系人列表获取完成后再启动 QQBot （ startAfterFetch ）” 的选项
2） 修复 smartRequest 方法中的 bug ，感谢 @chenhouwu 反馈
3） 增加 “用于在JetBrains PyCharm IDE环境下进行开发时的一个启动文件” ，感谢 @SuperMarioSF 提供此文件
4） 增加 requirements.txt ，感谢 @gtt116

**Comment by qqdaiyu55** [comment]
**v2.1.10 feedback**: 启动后不停读取更新群成员列表, kswapd0 高cpu占用(98%左右). `sys: centos 7.3.1611, kernel:  4.10.1-1.el7.elrepo.x86_64`
**v2.1.8 feedback**: 这个bug因为 v2.1.10 没有登陆成功所以只在之前版本测过。一个返回的字符串str通过print查看是正常的，但是`bot.SendTo(contact, str)`没有发送成功 。这在早期版本从没出现过问题，不知道是不是因为新版本对消息处理方法的变化导致的。具体内容作者可以联系我下qq 619045405, 谢谢 :)

**Comment by SuperMarioSF** [comment]
@qqdaiyu55 关于你提到的kswapd0高占用的问题，多半是内核上有些问题。很显然qqbot不可能直接去碰内核部分。至于不停更新群成员列表请给更详细的信息。

**Comment by pandolia** [comment]
v2.1.10 更新一次群成员列表后平均 sleep 2 秒左右（有两个线程并行的更新，一个 sleep 5 秒， 一个 sleep 3 秒），应该不至于引起高 cpu 占用。

**Comment by qqdaiyu55** [comment]
是偶发性，我reboot+reinstall后就好了，但是**v2.1.8 feedback**的问题再v2.1.10版本也存在

**Comment by SuperMarioSF** [comment]
@qqdaiyu55
如果把str作为变量名可能会引起问题。
此外，是否尝试过这样传入参数？
```python
bot.SendTo(contact, str(msg))
```

**Comment by qqdaiyu55** [comment]
@SuperMarioSF 问题已经解决，是发的消息只能是string类型，而我传的消息是unicode类型，所以导致发不出去。
