### ISSUE TITLE
优化消息分段

### ISSUE THREAD

**Issue by chenhouwu** [pandolia/qqbot#97]
同样一段消息，在 python2中不需要分段
在python3中需要分为好几段，
**英文字母越多差别越明显**。

期望通过优化，每个消息可以更长一点。

没读代码，但是相信是unicode和utf8的缘故，

**Comment by pandolia** [comment]
你是哪个版本的？2.1.13版的改了一下，python2 中是长度为 600 的utf8 bytes，python3中是长度为 200的unicode。也就是说，python2中可以发 200个汉字或者600个字母，python3中可以发200个汉字或200个字母。

**Comment by pandolia** [comment]
确实是英文字母越多差别越大。

**Comment by chenhouwu** [comment]
所以需要优化一下，
否则英文字母一多，消息就被分割得特别零碎。
建议：
以空格/换行符为分割，增量计算是否超长。
这样可以消息可以尽可能地长，且不会分割得很乱。

**Comment by chenhouwu** [comment]
如果能够进一步定制分割符，那就更满意了，
并将空格/换行符作为默认分隔符，以保持api兼容性。

**Comment by chenhouwu** [comment]
@pandolia 这块你怎么决定的？

**Comment by chenhouwu** [comment]
@pandolia 这个issue决定accept还是reject呢？
我作为上层应用，需要你的决策再做相应的对策

**Comment by pandolia** [comment]
@chenhouwu 我想还是统一成发 200个汉字或者600个字母，再多可能发不出去了，或者你可以测试一下最多能发多少个。至于你说的分隔符，我想也要给个范围，比方说 580~620 之间有分隔符才按分隔符分割，没有就按 600 分割。也不能绝对的就按分隔符去分割，因为万一碰到没有分隔符的就傻眼了。
话说有这么复杂的需求，最好是上层应用自己分割完了再发啊。
底层库能做的最多就是把一次能发的消息尽量长一些。

**Comment by pandolia** [comment]
@chenhouwu 能否描述一下你需要发什么样的消息，需要这么长？

**Comment by chenhouwu** [comment]
1. 嗯，这样比较好。
    >我想也要给个范围，比方说 580~620 之间有分隔符才按分隔符分割
2. 没有分隔符就以现在实现按的长度限制分割就行了
   >万一碰到没有分隔符的就傻眼了。
4. 现在的情况是，在以前的版本中可以一次发完的，现在库中强行200个字符分割成多段，这个上层应用是没法控制的。
    >话说有这么复杂的需求，最好是上层应用自己分割完了再发啊。

    所以我才建议实现：
    >增量计算**utf8编码后的**字符是否超长。

**Comment by chenhouwu** [comment]
>能否描述一下你需要发什么样的消息，需要这么长？

就是一长段话，里面有一些文字介绍，有一些资源的url链接。

**Comment by pandolia** [comment]
@chenhouwu v2.1.17已优化消息分段，一次发消息内容最长为 240 个汉字或 720 个英文，也就是 utf8 编码后的长度不能超过 720 ，超过此长度将被分段，按以下原则分段：如果 620~720之间有空格字符（空格，\t，\n等），则按最后一个空格进行分割，否则，按 720 进行分割。

另外，如果你想用自己的分段函数，可以这样按以下方式覆盖 basicqsession.py 中的 Partition 函数：

    def myPartition(msg):
        return msg[:200], msg[200:]

    import qqbot.basicqsession; basicqsession.Partition=myPartition

默认的 Partition 函数定义在 common.py 中，代码如下：

    def Partition(msg):
        if PY3:
            msg = msg.encode('utf8')
    
        n = 720
    
        if len(msg) < n:
            f, b = msg, ''
        else:
            for i in range(n-1, n-101, -1):
                if msg[i].isspace():
                    f, b = msg[:i], msg[i:]
                    break
            else:
                f, b = msg[:n], msg[n:]
        
        if PY3:
            return f.decode('utf8'), b.decode('utf8')
        else:
            return f, b

**Comment by chenhouwu** [comment]
```
if PY3:
        return f.decode('utf8'), b.decode('utf8')
```

在py3下，这里可能有问题。因为下面的代码中b是unicode，所以没法再decode。
```
 if len(msg) < n:
        f, b = msg, ''
```

**Comment by chenhouwu** [comment]
经测试，确实有问题，fix如下：
```
 if len(msg) < n:
        f, b = msg, ''.encode('utf8')
```

**Comment by pandolia** [comment]
感谢提醒。已经修改了代码。
