### ISSUE TITLE
群成员能判断是否管理员/群主吗?

### ISSUE THREAD

**Issue by jim4node** [pandolia/qqbot#98]
群成员能判断是否管理员/群主吗? 我看了 QSession:fetchGroupMemberTable , 貌似没有获取这方面的信息, 未来能加上吗?
我的应用场景是这样的: 拥有群管理权限的群成员, 可以发送特殊指令"暂停"或"恢复" QQBot 的自动应答机制; 若普通群员发送这些指令, 则不得响应; 所以需要在 onQQMessage 中判断 member 的管理权限

**Comment by pandolia** [comment]
刚才上传的源码已增加成员的 role 属性，详见 https://github.com/pandolia/qqbot/blob/master/group-member-ex-attr.md 。尚未上传到 pip 。

**Comment by jim4node** [comment]
今天升级了, role 很管用, 谢谢! 有个小建议, 如果能加上 roleId 就更好了 (即从服务器获取的 'role' ), 这样在用户程序里还能自定义中文角色, 而且比较角色时用 roleId 比用汉字高效吧

**Comment by pandolia** [comment]
v2.1.15版已增加 m.role_id 属性
