### ISSUE TITLE
HTTP API的返回结果

### ISSUE THREAD

**Issue by lvsenlin** [pandolia/qqbot#99]
如题
没写过python，束手无策

**Comment by pandolia** [comment]
HTTP API的返回结果和 qq 命令的输出结果是完全一样的。你先测试一下相关的 qq 命令就知道了。

**Comment by pandolia** [comment]
比方说： http://127.0.0.1:8188/send/buddy/jack/hello 的返回结果，和命令 qq send buddy jack hello 的输出结果是完全一样的。

**Comment by lvsenlin** [comment]
现在的返回结果在日志中，在response中才好用

**Comment by pandolia** [comment]
v2.1.14版已经完善了 HTTP-API 的返回结果，所有 API 都返回 json 。效果如下：

![default](https://cloud.githubusercontent.com/assets/13767061/24802846/f6eaf3cc-1bdb-11e7-9739-87834b885431.png)

**Comment by lvsenlin** [comment]
thank you~
